Refactor ignore platform reqs checks
composer/composer pull request #10079
Opened 2021-08-26 20:56 UTC by herndlm

Introduces a `PlatformRequirementFilter` with methods that help to decide if a requirement is ignored or not as discussed in #10045 but without changing behaviour.
The idea behind this is to be able to adapt simple wildcard or regex ignores in a follow-up.

I changed as much as needed so that the filter and its logic is used everywhere where the `bool|string[]` config was before, because it felt inconsistent otherwise. But I also tried to change as less as possible which is the reason the argument is nullable in some cases and falls back to the nothing filter then or is defined like that in the constructor.
Initially I only had one filter class, but this became already too complex and mixed regarding types in my opinion, so I split responsibilities into dedicated filter classes, which is of course more code/classes but way simpler to read/understand/test.

2021-08-28 09:19 UTC, herndlm commented
Nevermind, had an idea to improve this, I'll adapt it and open it for review then

2021-08-29 07:29 UTC, herndlm commented
Is it safe to do those changes from an API perspective? E.g. could plugins use those classes? And if so - if they extend from them too, can we even change any non-private signatures?

2021-08-29 12:45 UTC, Seldaek requested changes
IMO it's mostly looking good, thanks for the work!

The few places I commented on it'd be good to keep the old API functional, but the other places are internal-enough that we shouldn't bother. When restoring setters for BC, we could add `trigger_error(E_USER_DEPRECATED...)` to those few places so people notice and migrate away.

Note that for the follow-up of adding wildcard support, using this code is probably a good idea to turn wildcards into regexes, we do this in a few places already: https://github.com/composer/composer/blob/master/src/Composer/Package/BasePackage.php#L251-L256

2021-08-29 12:45 UTC, Seldaek commented on src/Composer/Installer.php
> -    public function setIgnorePlatformRequirements($ignorePlatformReqs)
I think it'd be good to keep the old method around here too for API compatibility, which would I guess simply call `PlatformRequirementFilter::fromBoolOrList($ignorePlatformReqs)`.

2021-08-29 12:45 UTC, Seldaek commented on src/Composer/Package/Version/VersionSelector.php
> -    public function findBestCandidate($packageName, $targetPackageVersion = null, $preferredStability = 'stable', $ignorePlatformReqs = false, $repoSetFlags = 0)
I think it'd be good to keep the supporting an array here too for API compatibility, which would I guess simply call `PlatformRequirementFilter::fromBoolOrList($ignorePlatformReqs)` if the arg is not of type `PlatformRequirementFilter`.

2021-08-29 12:45 UTC, Seldaek commented on src/Composer/Autoload/AutoloadGenerator.php
> -    public function setIgnorePlatformRequirements($ignorePlatformReqs)
I think it'd be good to keep the old method around here too for API compatibility, which would I guess simply call `PlatformRequirementFilter::fromBoolOrList($ignorePlatformReqs)`.

2021-08-29 13:49 UTC, herndlm commented
> IMO it's mostly looking good, thanks for the work!

I'm very glad to hear that, thx!

> The few places I commented on it'd be good to keep the old API functional, but the other places are internal-enough that we shouldn't bother. When restoring setters for BC, we could add `trigger_error(E_USER_DEPRECATED...)` to those few places so people notice and migrate away.

Yes, keeping BC here is luckily as simple as that. I adapted it and added `@deprecated` phpdoc annotations too.

> Note that for the follow-up of adding wildcard support, using this code is probably a good idea to turn wildcards into regexes, we do this in a few places already: https://github.com/composer/composer/blob/master/src/Composer/Package/BasePackage.php#L251-L256

Thx for the hint, I stumbled over that already yesterday and thought of using it (+ adding a few tests). Previously I was looking at [`fnmatch`](https://www.php.net/manual/en/function.fnmatch.php), which is not available on exotic platforms apparently though.

2021-08-29 14:34 UTC, Seldaek approved these changes

2021-08-29 14:37 UTC, Seldaek commented
I can squash on merge. I'll leave this open until master starts targetting 2.2 though. If you want to do a follow-up PR with the pattern matching you could already open a second one that is based on this branch?

2021-08-29 17:39 UTC, herndlm commented
Sorry, rebased with auto-squash after all.. I was afraid this might otherwise mess up the new branch / PR on merge and wanted to start clean there.

2021-08-29 18:01 UTC, Seldaek commented
No worries :)

2021-09-05 17:14 UTC, herndlm commented
rebased to fix a conflict

2021-09-26 10:29 UTC, helhum approved these changes
Nice cleanup imho

2021-10-12 21:06 UTC, imme-emosol commented
My comment https://github.com/composer/composer/issues/9534#issuecomment-941293738 might affect this issue.

2021-10-13 07:14 UTC, herndlm commented
> My comment [#9534 (comment)](https://github.com/composer/composer/issues/9534#issuecomment-941293738) might affect this issue.

I'm not sure if it does or if I missed something. The intention here was "just" to refactor the platform reqs checks and prepare them to add more functionality like glob like wildcards for which I added another PR. I wasn't even aware of the feature-request regarding upper bounds. Should be independent at least if I'm not mistaken. And would be easier to implement afterwards for sure.

2021-10-13 08:06 UTC, imme-emosol commented
> > My comment [#9534 (comment)](https://github.com/composer/composer/issues/9534#issuecomment-941293738) might affect this issue.
> 
> I'm not sure if it does or if I missed something. [...] Should be independent at least if I'm not mistaken. And would be easier to implement afterwards for sure.

You are right in that the code changes made here will probably make things easier anyway indeed.

2021-10-18 08:52 UTC, herndlm commented
rebased to fix a confict and added the inheratiance -> composition changes in a fixup as I requested a re-review already anyways

2021-11-03 09:02 UTC, herndlm commented
rebased and should be ready again for review

2021-11-10 20:35 UTC, Seldaek requested changes
Looks like a great improvement to me, just the method name nitpick and then happy to finally merge this :)

2021-11-10 20:35 UTC, Seldaek commented on src/Composer/Filter/PlatformRequirementFilter/PlatformRequirementFilterInterface.php
> +    public function isReqIgnored($req);
If you don't mind, I think this would be better as simply isIgnored?

```suggestion
    public function isIgnored($req);
```

2021-11-11 08:42 UTC, herndlm commented on src/Composer/Filter/PlatformRequirementFilter/PlatformRequirementFilterInterface.php
> +    public function isReqIgnored($req);
Definitely better, `req` is not needed in this context

2021-11-11 11:24 UTC, merged

2021-11-11 11:24 UTC, Seldaek commented
Thanks!

2021-11-11 11:46 UTC, herndlm commented
Great thx, I'll rebase and make the wildcard-follow-up feature ready soon then :)