WIP: [FEATURE] Configure automatic yes for composer.json in upper directory
composer/composer pull request #10307
Opened 2021-11-24 09:03 UTC by CDRO

Resolves: #10299 

I'm far off being done, since I haven't got any tests for this new feature (and don't even know if you'd want to have it), so it'll stay at WIP state for now.

2021-11-24 09:15 UTC, herndlm commented
Hi, it looks like I'm the author of the commit, which I'm not :) can you rebase and fix that please?

2021-11-24 09:17 UTC, stof commented on src/Composer/Console/Application.php
> +        $alwaysUseParentComposerIfNoneAvailable = $composer->getConfig()->get('use-parent-dir-composer') || false;
`|| false` is weird here. Are you using the javascript way of defining default values ?

2021-11-24 09:17 UTC, CDRO commented
Yeah, I've seen that, but I don't know why? I've rebased my master branch and suddenly you were the author of my commit ¯\＿(ツ)＿/¯ I'll try and fix this.

2021-11-24 09:19 UTC, CDRO commented on src/Composer/Console/Application.php
> +        $alwaysUseParentComposerIfNoneAvailable = $composer->getConfig()->get('use-parent-dir-composer') || false;
Thanks for your feedback.

This was actually suggested by Php Inspections (EA Extended), instead of using `?: false` (as `??` is not available in PHP 5.3 yet)

2021-11-24 13:12 UTC, stof commented on src/Composer/Console/Application.php
> +        $alwaysUseParentComposerIfNoneAvailable = $composer->getConfig()->get('use-parent-dir-composer') || false;
if you put a value in the default config, it will return a value AFAICT.

2021-11-24 13:23 UTC, CDRO commented on src/Composer/Console/Application.php
> +        $alwaysUseParentComposerIfNoneAvailable = $composer->getConfig()->get('use-parent-dir-composer') || false;
From what I can tell, looking at `Config.php`, which actually gets the value and `ConfigCommand.php` which sets the value, there is no way to set a default value for something, so I could drop this if default value setting if I ensure something is set in `SelfUpdateCommand.php`?
![image](https://user-images.githubusercontent.com/6471286/143245651-b0fdb018-5d44-4a1c-88dd-f1b88dd22d25.png)

2021-11-24 13:34 UTC, stof commented on src/Composer/Console/Application.php
> +        $alwaysUseParentComposerIfNoneAvailable = $composer->getConfig()->get('use-parent-dir-composer') || false;
`Config::$defaultConfig` is where the default config is set, so that `$this->config[$key]` is always set.

2021-11-24 13:36 UTC, stof commented on src/Composer/Console/Application.php
> +        $alwaysUseParentComposerIfNoneAvailable = $composer->getConfig()->get('use-parent-dir-composer') || false;
and if you want extra safety, add this config key in the section `booleans without env var support` of the switch.

2021-11-24 13:42 UTC, CDRO commented on src/Composer/Console/Application.php
> +        $alwaysUseParentComposerIfNoneAvailable = $composer->getConfig()->get('use-parent-dir-composer') || false;
Yes and yes, thanks very much!

2021-11-26 08:56 UTC, Seldaek requested changes
Looks fine to me but a few things need to be improved:

- Please allow false/true/'prompt' as values. That way people like me who never actually want this feature can turn it off and just get a new composer.json in a subdir whenever needed without having to confirm.
- Please add the new config value to the doc/06-config.md docs and res/composer-schema.json

2021-11-26 08:56 UTC, Seldaek commented on src/Composer/Config.php
> +        'use-parent-dir-composer' => false,
```suggestion
        'use-parent-dir-composer' => 'prompt',
```

2021-11-26 08:56 UTC, Seldaek commented on src/Composer/Config.php
> +            case 'use-parent-dir-composer':
This should move below into its own section handling true/false/prompt as value.

2021-11-26 08:56 UTC, Seldaek commented on src/Composer/Console/Application.php
>          if ($io->isInteractive() && !$newWorkDir && !in_array($commandName, array('', 'list', 'init', 'about', 'help', 'diagnose', 'self-update', 'global', 'create-project', 'outdated'), true) && !fi
```suggestion
        if ($io->isInteractive() && $alwaysUseParentComposerIfNoneAvailable !== false && !$newWorkDir && !in_array($commandName, array('', 'list', 'init', 'about', 'help', 'diagnose', 'self-update', 'global', 'create-project', 'outdated'), true) && !file_exists(Factory::getComposerFile())) {
```

2021-11-26 08:56 UTC, Seldaek commented on src/Composer/Console/Application.php
> +                    if ($alwaysUseParentComposerIfNoneAvailable || $io->askConfirmation('<info>No composer.json in current directory, do you want to use the one at '.$dir.'?</info> [<comment>Y,n</com
```suggestion
                    if ($alwaysUseParentComposerIfNoneAvailable === true || $io->askConfirmation('<info>No composer.json in current directory, do you want to use the one at '.$dir.'?</info> [<comment>Y,n</comment>]? ')) {
```

2021-11-26 12:32 UTC, CDRO commented on src/Composer/Config.php
> +            case 'use-parent-dir-composer':
I've looked at this and the only comparable option I've seen to this is 'store-auths' which does not have it's own section, can I assume that the default case will handle this properly?

2021-11-26 12:35 UTC, CDRO commented on src/Composer/Console/Application.php
>          if ($io->isInteractive() && !$newWorkDir && !in_array($commandName, array('', 'list', 'init', 'about', 'help', 'diagnose', 'self-update', 'global', 'create-project', 'outdated'), true) && !fi
I'm not sure about this one, since if you decide to not use this option, you would still probably want to be asked if you want to use the composer.json in the upper directory, setting this option to false will simpy default to telling you that there is no composer.json.

2021-11-27 19:30 UTC, Seldaek commented on src/Composer/Config.php
> +            case 'use-parent-dir-composer':
Yup it should be fine you're right.

2021-11-27 19:32 UTC, Seldaek commented on src/Composer/Console/Application.php
>          if ($io->isInteractive() && !$newWorkDir && !in_array($commandName, array('', 'list', 'init', 'about', 'help', 'diagnose', 'self-update', 'global', 'create-project', 'outdated'), true) && !fi
Yes, I want it to tell me there is no composer.json, because it then allows me to use `composer require` in a subdir to create a new composer.json without having to say no, as that one won't say there is no composer.json it'll just create one..

2021-12-04 14:00 UTC, merged

2021-12-04 14:00 UTC, Seldaek commented
OK, had a play with it and spotted a few more issues but it's all resolved now, thanks!