Add allow-plugins config value
composer/composer pull request #10314
Opened 2021-11-25 21:01 UTC by Seldaek

Fixes #5659

Still a few TODOs / open questions

- Currently this warns on every operation once you have a plugin which is not enabled, I am not sure if this gets annoying or not. Are there cases where you want to have plugins installed but not enable them? Or is this only a safety net?

![image](https://user-images.githubusercontent.com/183678/143499308-e99636e4-f547-4067-ba78-70a220e7606c.png)

- Probably would be nicer if it instead prompted the user if the plugin should be added or not when something doesn't match the allow-plugins rules. Default to no of course.. Then we could modify the config in band and proceed activating the plugin if desired. Otherwise store it in a disallow-plugins list to make explicit those you don't wanna hear about again?

- Needs comprehensive docs for sure, and that new `/allow-plugins` shortlink on getcomposer.org

2021-11-26 10:13 UTC, stof commented on src/Composer/Command/ConfigCommand.php
> +                    if (!is_array($vals)) {
what about booleans ?

2021-12-07 09:34 UTC, Seldaek commented
Latest version of the PR does prompt the user whether new unknown plugins should be enabled if interactive. When non-interactive and allow-plugins is not set at all, it allows all plugins for BC. When non-interactive and allow-plugins is set but does not include a given package, that package is not allowed.

Now I do wonder if we shouldn't build in some time-based feature switch in there that makes it forbid all plugins if `allow-plugins` is not set in 6months or 1year from now? That way 2.2.0 and above would keep working BC but would warn users, getting people to slowly add that config, and then at some point it'd remove the BC layer and default `allow-plugins` to `false`.

Any thoughts on this last point?

2021-12-07 11:12 UTC, naderman commented
I agree with adding a mechanism to get people to start adding the setting in due time.

2021-12-07 11:15 UTC, naderman requested changes

2021-12-07 11:15 UTC, naderman commented on src/Composer/Config.php
> +                    // then merging local one again to make sure the values from local win over global ones for keys present in both
Not sure I understand this logic? Why not just do it once, sounds like that should have the same effect?

2021-12-07 11:15 UTC, naderman commented on src/Composer/Plugin/PluginManager.php
> +        $this->allowGlobalPluginRules = $this->parseAllowedPlugins($globalComposer ? $globalComposer->getConfig()->get('allow-plugins') : false);
I wonder how global plugin allow should even work? Merging the setting with local and applying to all plugins executed in this process or should the global setting apply to global plugins and local setting to local plugins?

2021-12-07 11:18 UTC, naderman commented on src/Composer/Plugin/PluginManager.php
> +                    switch ($answer = $this->io->ask('<warning>Do you trust "'.$package.'" to execute code and wish to enable the plugin now? [y,n,d,?]</warning> ', '?')) {
I think this should probably clarify it will add the name to the composer.json for future execution?

2021-12-07 12:44 UTC, Seldaek commented on res/composer-schema.json
> +                    "description": "This is an array of package names which are allowed to be loaded as plugins, or true to allow all, false to allow none, defaults to true.",
```suggestion
                    "description": "This is an object of {\"pattern\": true|false} with packages which are allowed to be loaded as plugins, or true to allow all, false to allow none. Defaults to {} which prompts when an unknown plugin is added.",
```

2021-12-07 12:47 UTC, Seldaek commented on src/Composer/Plugin/PluginManager.php
> +        $this->allowGlobalPluginRules = $this->parseAllowedPlugins($globalComposer ? $globalComposer->getConfig()->get('allow-plugins') : false);
Right now it does apply global setting to global plugins and local to local plugins. Note that this refers to the `composer  global` installed plugins. The global config.json would just be merged in both local and global composer configs.

I think it's fine as is. If you add a plugin via `composer global require ...` it will prompt you and add it in that composer.json and it works.

2021-12-07 12:49 UTC, Seldaek commented on src/Composer/Plugin/PluginManager.php
> +                    switch ($answer = $this->io->ask('<warning>Do you trust "'.$package.'" to execute code and wish to enable the plugin now? [y,n,d,?]</warning> ', '?')) {
Yeah this is clarified in the help section. I am not sure how to formulate it in a way that's still short enough to avoid a wall of text as prompt here :/

2021-12-07 12:51 UTC, Seldaek commented on src/Composer/Config.php
> +                    // then merging local one again to make sure the values from local win over global ones for keys present in both
The thing is the patterns are looked up in order of declaration, so if you have `composer/*: true` locally but `composer/bla: false` in global config you want to make sure the local `composer/*` takes precedence. But if both define the same name doing `array_merge(local, global)` would overwrite the value of local conf with global one, which is then fixed by doing `array_merge(local, global, local)`

2021-12-07 13:25 UTC, naderman commented on src/Composer/Plugin/PluginManager.php
> +        $this->allowGlobalPluginRules = $this->parseAllowedPlugins($globalComposer ? $globalComposer->getConfig()->get('allow-plugins') : false);
I agree that's fine but this may require a bit more documentation? Can also add that when the first confused person shows up ;-)

2021-12-07 16:07 UTC, bmack commented
Hey @Seldaek ,

> Now I do wonder if we shouldn't build in some time-based feature switch in there that makes it forbid all plugins if allow-plugins is not set in 6months or 1year from now? That way 2.2.0 and above would keep working BC but would warn users, getting people to slowly add that config, and then at some point it'd remove the BC layer and default allow-plugins to false.

I was just reviewing your PR and was wondering why you put the timing check in the code, instead of using versioning. Otherwise people could stick with old versions (of course they should not do that), instead of faking their system time to make plugins work without configuration anymore :)

2021-12-07 20:59 UTC, Seldaek commented
@bmack why would anyone want to do this though? I mean if you really don't care for security you can do `composer config --global allow-plugins true` to just tell it to run anything. **NOT RECOMMENDED** but it's there.

2021-12-07 20:59 UTC, naderman commented on src/Composer/Plugin/PluginManager.php
> +                    switch ($answer = $this->io->ask('<warning>Do you trust "'.$package.'" to execute code and wish to enable the plugin now? [y,n,d,?]</warning> ', '?')) {
```suggestion
                    switch ($answer = $this->io->ask('<warning>Do you trust "'.$package.'" to execute code and wish to enable it now? (writes allow-plugins to composer.json) [y,n,d,?]</warning> ', '?')) {
```

2021-12-07 21:52 UTC, naderman approved these changes

2021-12-07 22:00 UTC, merged

2021-12-07 22:27 UTC, bmack commented
@Seldaek well, personally, I'd never do such things (but you know, people come up with stupid ideas to solve their issues). Also: I'd never put this in a global setting at all (my CI wouldn't have the plugins enabled, but I have it in my global config - would lead to inconsistencies), but I see this 100% on a per-project config level, and love it.

Doing this switch not via versioning but by date seems odd. I just wondered why we shouldn't stick to sem-ver here, instead of going with a fixed date "deadline". In any case: Thanks a bunch, very much looking forward to this!

2021-12-07 22:34 UTC, naderman commented
@bmack We want this in 2.2 LTS so that this will apply to the majority of all users within a few months. As 2.3 is going to drop support for lots of old PHP versions, dependencies etc., we would have to introduce the requirement for allow-plugins in a 2.2.x release. But that would mean people who don't want the requirement have to stay on an outdated version missing bugfixes on the 2.2 LTS line, which we want to discourage them from doing.

So instead it'll be timed and included in all 2.2 releases, and worst case as Jordi described it can be disabled.

2022-01-10 22:08 UTC, GPHemsley-RELX commented
Is there a command that can be run that will do nothing but prompt about updating the `allow-plugins` config?

2022-01-11 08:23 UTC, Seldaek commented
`composer show` for example would load the plugins and prompt, without other side effect.