Add support for ignoring the upper bound of platform requirements using "name+" notation
composer/composer pull request #10318
Opened 2021-11-28 12:37 UTC by Seldaek

e.g. `--ignore-platform-req=php+` ignores the upper bound of the php requirements.

Fixes https://github.com/composer/composer/issues/9534

2021-11-28 13:04 UTC, derrabus commented
Thank you for working on this feature!

2021-11-28 13:37 UTC, herndlm commented
Hehe, I had a similar idea. Really glad to see that the ignore platform reqs refactoring was helpful :)

2021-11-28 14:40 UTC, Seldaek commented
@herndlm yeah this definitely enabled a much easier implementation for this use case.

2021-12-06 15:16 UTC, naderman requested changes

2021-12-06 15:16 UTC, naderman commented on doc/03-cli.md
> +  allow installation, but on PHP 5.6 it would still fail.
```suggestion
  does not fulfill it. Multiple requirements can be ignored via wildcard. Appending
  a `+` makes it only ignore the upper-bound of the requirements. For example, if a package
  requires `php: ^7`, then the option `--ignore-platform-req=php+` would allow installing on PHP8,
  but installation on PHP 5.6 would still fail.
```

2021-12-06 15:16 UTC, naderman commented on doc/03-cli.md
> +  allow installation, but on PHP 5.6 it would still fail.
```suggestion
  does not fulfill it. Multiple requirements can be ignored via wildcard. Appending
  a `+` makes it only ignore the upper-bound of the requirements. For example, if a package
  requires `php: ^7`, then the option `--ignore-platform-req=php+` would allow installing on PHP8,
  but installation on PHP 5.6 would still fail.
```

2021-12-06 15:16 UTC, naderman commented on src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php
> +            $constraint = new MultiConstraint(array($constraint, new Constraint('>=', $last->getEnd()->getVersion())), false);
want to optimize/simplify this one here?

2021-12-06 15:16 UTC, naderman commented on tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list-upper-bounds.test
> +        "ext-foo-bar": "5.0.3"
can you add one more require/provide here that tests it actually throws the right error if an extension is present with a version number too low?

2021-12-06 20:19 UTC, Seldaek commented on src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php
> +            $constraint = new MultiConstraint(array($constraint, new Constraint('>=', $last->getEnd()->getVersion())), false);
Not sure it matters?

2021-12-06 20:25 UTC, Seldaek commented on tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list-upper-bounds.test
> +        "ext-foo-bar": "5.0.3"
Done 👍

2021-12-06 20:25 UTC, naderman commented on src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php
> +            $constraint = new MultiConstraint(array($constraint, new Constraint('>=', $last->getEnd()->getVersion())), false);
Just the usual question: what does it cost to optimize vs how often it gets checked later, also wonder if this is usually the same constraint in a lot of packages and caching the result instead of working with intervals matters performance wise? But probably all only answerable with benchmarks.

2021-12-06 20:34 UTC, Seldaek commented on src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php
> +            $constraint = new MultiConstraint(array($constraint, new Constraint('>=', $last->getEnd()->getVersion())), false);
Yeah given this is very special use I don't think it's worth obsessing over the perf aspects too much.

2021-12-06 23:21 UTC, naderman commented on tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list-upper-bounds.test
> +    - b/b 1.0.1 requires ext-foo-bar 10.* -> it is missing from your system. Install or enable PHP's foo-bar extension.
This message seems wrong now? ext-foo-bar is present, the version is just too low?

2021-12-07 08:51 UTC, Seldaek commented on tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list-upper-bounds.test
> +    - b/b 1.0.1 requires ext-foo-bar 10.* -> it is missing from your system. Install or enable PHP's foo-bar extension.
Yeah that was kinda unrelated bug in Problem output, added a commit that fixes it.

2021-12-07 10:17 UTC, naderman commented on src/Composer/DependencyResolver/Problem.php
> +                    $error = 'it has the wrong version ('.$version.') installed';
```suggestion
                    $error = 'it has the wrong version installed ('.$version.')';
```

Hard to read otherwise

2021-12-07 10:18 UTC, naderman commented on tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list-upper-bounds.test
> +    - b/b 1.0.1 requires ext-foo-bar 10.* -> it has the wrong version (5.0.3 provided by __root__ 1.0.0+no-version-set) installed. Install or enable PHP's foo-bar extension.
```suggestion
    - b/b 1.0.1 requires ext-foo-bar 10.* -> it has the wrong version (5.0.3 provided by __root__ 1.0.0+no-version-set) installed. Install or enable PHP's foo-bar extension.
```

That last part is still a bit confusing but I guess okay as long as the first part is there?

2021-12-07 12:23 UTC, Seldaek commented on tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list-upper-bounds.test
> +    - b/b 1.0.1 requires ext-foo-bar 10.* -> it has the wrong version (5.0.3 provided by __root__ 1.0.0+no-version-set) installed. Install or enable PHP's foo-bar extension.
Fixed that as well 👍🏻

2021-12-07 13:07 UTC, merged

2021-12-15 12:55 UTC, derickr commented on doc/03-cli.md
> +  but installation on PHP 5.6 would still fail.
So it's PHP 5.6, but then PHP8. There is a space missing there ;-)

2021-12-19 11:36 UTC, Seldaek commented on doc/03-cli.md
> +  but installation on PHP 5.6 would still fail.
Will fix ;)

2023-11-21 12:45 UTC, dg commented
It seems to unnecessarily print the error message `Cannot use texy/texy's latest version v3.2.0 as it requires php 8.1 - 8.3 which is not satisfied by your platform.`, although it does install the library.

2023-11-21 12:50 UTC, Seldaek commented
@dg Yeah that warning is handled somewhere else, please open a new issue with details how to repro.