Add documentation on platform dependencies
composer/composer pull request #10313
Opened 2021-11-25 17:16 UTC by helhum

2021-11-25 17:26 UTC, helhum commented
Updated version of #9965

2021-11-26 10:03 UTC, naderman requested changes
Thanks for the docs, I know I edited a lot, but really wouldn't have been this easy if you hadn't already provided all the content ;-)

2021-11-26 10:03 UTC, naderman commented on doc/articles/composer-platform-dependencies.md
> +the `composer-runtime-api` version nor the `composer-plugin-api` was changed.
```suggestion
Starting with Composer 2.2.0, a new platform package called `composer` is available, which represents the exact
Composer version that is executed. Packages depending on this platform package, can therefore depend on (or conflict
with) individual Composer versions, to cover edge cases, where neither the `composer-runtime-api` version nor the
`composer-plugin-api` was changed.
```

2021-11-26 10:03 UTC, naderman commented on doc/articles/composer-platform-dependencies.md
> +to at least `^2.2.0`, to get a more meaningful error message with older Composer versions.
```suggestion
Because this option was introduced with Composer 2.2.0, it is recommended to add a `composer-plugin-api` depedency on
at least `>=2.2.0`, to provide a more meaningful error message for users running older Composer versions.
```

2021-11-26 10:03 UTC, naderman commented on doc/articles/composer-platform-dependencies.md
> +over depending on concrete Composer versions using the `composer` platform package.
```suggestion
In general it is always recommended to depend on `composer-plugin-api` or `composer-runtime-api` over depending on concrete Composer versions using the `composer` platform package.
```

2021-11-26 10:04 UTC, naderman commented
Eh I see Jordi didn't wait for me to actually review as he asked, so my changes conflict with some of his. So ideally revert whatever @Seldaek tweaked in the docs and then just apply my suggestions?

2021-11-26 11:33 UTC, helhum commented
Thanks for the doc updates. I can now take care integrating them cleanly, resolving the conflicts. What I wasn't able to figure out is what PHPStan's complaint is about. So that will be something you'll need to fix in the end.

2021-11-26 11:40 UTC, stof commented on tests/Composer/Test/Repository/PlatformRepositoryTest.php
> +    public static function getPlatformPackages()
name you data provider `provide*`, which avoids having to declare its precise return type in the composer phpstan configuration (defining exact return types on data providers is useless, as phpstan won't compare them to the signature of test methods anyway)

2021-11-26 11:41 UTC, helhum commented on tests/Composer/Test/Repository/PlatformRepositoryTest.php
> +    public static function getPlatformPackages()
Ah, thanks, will do!

2021-11-26 11:54 UTC, helhum commented on tests/Composer/Test/Repository/PlatformRepositoryTest.php
> +    public static function getPlatformPackages()
This worked out, thanks!

2021-11-26 11:56 UTC, helhum commented
@naderman I integrated your suggestions now (thanks all of them made a lot of sense), merged with @Seldaek changes where applicable and fixed some additional typos that I found after that. 
Since PHPStan is also happy now, I think this is good to go as well?

2021-11-26 19:02 UTC, naderman commented
@helhum great thanks!

2021-11-26 19:03 UTC, naderman approved these changes

2021-11-26 21:44 UTC, naderman approved these changes

2021-11-26 21:44 UTC, naderman commented on doc/articles/composer-platform-dependencies.md
> +thus the version of `composer-runtimeapi` s also increased independently from Composer's version.
```suggestion
Similar to `composer-plugin-api`, not every Composer release adds new runtime features,
thus the version of `composer-runtimeapi` is also increased independently from Composer's version. 
```

2021-11-26 21:44 UTC, naderman commented on doc/articles/composer-platform-dependencies.md
> +`composer-plugin-api` was changed.
```suggestion
Starting with Composer 2.2.0, a new platform package called `composer` is available, which represents the exact
Composer version that is executed. Packages depending on this platform package can therefore depend on (or conflict
with) individual Composer versions to cover edge cases where neither the `composer-runtime-api` version nor the
`composer-plugin-api` was changed.
```

2021-11-26 21:44 UTC, naderman commented on doc/articles/composer-platform-dependencies.md
> +at least `>=2.2.0`, to provide a more meaningful error message for users running older Composer versions.
```suggestion
Because this option was introduced with Composer 2.2.0, it is recommended to add a `composer-plugin-api` dependency on
at least `>=2.2.0` to provide a more meaningful error message for users running older Composer versions.
```

2021-11-26 21:44 UTC, naderman commented on doc/articles/composer-platform-dependencies.md
> +over depending on concrete Composer versions using the `composer` platform package.
```suggestion
In general, depending on `composer-plugin-api` or `composer-runtime-api` is always recommended
over depending on concrete Composer versions with the `composer` platform package.
```

2021-11-27 13:26 UTC, merged

2021-11-27 13:27 UTC, Seldaek commented
Thanks everyone!