[2.3] Add completion to commands
composer/composer pull request #10320
Opened 2021-11-30 00:16 UTC by GromNaN

Fix #10292

Code requires `symfony/console >= 5.4` to work and `PHP >= 7.1` to not fail (`void` return type).

2021-11-30 00:21 UTC, GromNaN commented on composer.json
> +        "symfony/console": "^5.4",
Only for testing.

2021-11-30 08:35 UTC, stof commented on composer.json
> -        "php": "^5.3.2 || ^7.0 || ^8.0",
Removing the PHP requirement is a no-go. From a dependency resolution PoV, this would support *more* versions than before

2021-11-30 10:06 UTC, Seldaek commented on composer.json
> -        "php": "^5.3.2 || ^7.0 || ^8.0",
It's pretty clear this is a temp commit that'll have to be removed before merge..

2021-11-30 10:27 UTC, GromNaN commented on composer.json
> -        "php": "^5.3.2 || ^7.0 || ^8.0",
Indeed, should not have committed these changes. We have to wait for the requirements to be updated in order to finish this PR

2021-11-30 10:35 UTC, GromNaN commented on src/Composer/Command/RunScriptCommand.php
> +                $suggestions->suggestValue($name);
array_keys

2021-11-30 10:38 UTC, GromNaN commented on src/Composer/Command/OutdatedCommand.php
> +            $suggestions->suggestValues(array_merge(array_keys($rootPackage->getRequires()), array_keys($rootPackage->getDevRequires())));
This code is duplicated in several commands and could be improved in the future. To factorise, we can add a protected method to the parent class, or create a `CompletionHelepr` class.

2021-11-30 10:40 UTC, Seldaek requested changes
Thanks for getting started on this, looking forward to having it available!

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/DependsCommand.php
> +            $rootPackage = $this->getComposer(true, $input->getOption('no-plugins'))->getPackage();
This is sufficient/equivalent:

```suggestion
            $rootPackage = $this->getComposer()->getPackage();
```

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/ExecCommand.php
> +            return "$e (local)";
I guess the local here may need to be stripped in the suggestions above? To get one you need to define a binary in the root package if you want to test.

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/OutdatedCommand.php
> +            $rootPackage = $this->getComposer(true, $input->getOption('no-plugins'))->getPackage();
Same here 
```suggestion
            $rootPackage = $this->getComposer()->getPackage();
```

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/OutdatedCommand.php
> +            $suggestions->suggestValues(array_merge(array_keys($rootPackage->getRequires()), array_keys($rootPackage->getDevRequires())));
This probably needs more work, I think it should probably list all packages which are installed.

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/RemoveCommand.php
> +            $rootPackage = $this->getComposer(true, $input->getOption('no-plugins'))->getPackage();
```suggestion
            $rootPackage = $this->getComposer()->getPackage();
```

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/RequireCommand.php
> +            $composer = $this->getComposer(true, $input->getOption('no-plugins'));
```suggestion
            $composer = $this->getComposer();
```

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/RequireCommand.php
> +            $suggestions->suggestValues(array('dist', 'source', 'auto'));
Can we reuse this perhaps? Maybe have some common options autocompleted in BaseCommand?

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/ShowCommand.php
> +            $rootPackage = $this->getComposer(true, $input->getOption('no-plugins'))->getPackage();
```suggestion
            $rootPackage = $this->getComposer()->getPackage();
```

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/ShowCommand.php
> +            $suggestions->suggestValues(array_merge(array_keys($rootPackage->getRequires()), array_keys($rootPackage->getDevRequires())));
This here should also include more than just root requirements, I'd say at least include installed packages, and perhaps platform packages too. Not sure if we want to go as far as allowing autocomplete from the full available list of packages.

Essentially either of these if blocks:
all 
https://github.com/composer/composer/blob/b93530d72ea5b1f3f6fd44b947b4ff5b8c338704/src/Composer/Command/ShowCommand.php#L208-L212

Or installed + platform
https://github.com/composer/composer/blob/b93530d72ea5b1f3f6fd44b947b4ff5b8c338704/src/Composer/Command/ShowCommand.php#L221-L226

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/UpdateCommand.php
> +            $rootPackage = $this->getComposer(true, $input->getOption('no-plugins'))->getPackage();
```suggestion
            $rootPackage = $this->getComposer()->getPackage();
```

2021-11-30 10:40 UTC, Seldaek commented on src/Composer/Command/UpdateCommand.php
> +            $suggestions->suggestValues(array_merge(array_keys($rootPackage->getRequires()), array_keys($rootPackage->getDevRequires())));
This should definitely list transient dependencies, so anything installed on top of the root requirements (I'd merge root requirements too as this might include things which are updatable but not necessarily installed)

2021-11-30 10:45 UTC, dkarlovi commented on src/Composer/Command/ShowCommand.php
> +            $suggestions->suggestValues(array_merge(array_keys($rootPackage->getRequires()), array_keys($rootPackage->getDevRequires())));
> Not sure if we want to go as far as allowing autocomplete from the full available list of packages.

Note that the **suggestions are further filtered down based on user input after Console suggest them**. If you have 200 packages, it will not just dump all 200 at you each time, they might be filtered down to 3 based on input.

IMO, we should start with suggesting everything that makes sense, otherwise it will be surprising why isn't it suggesting a thing you know is installed.

2021-11-30 10:50 UTC, Seldaek commented on src/Composer/Command/ShowCommand.php
> +            $suggestions->suggestValues(array_merge(array_keys($rootPackage->getRequires()), array_keys($rootPackage->getDevRequires())));
Yes but returning the full list of packages from packagist.org would be >300K items, maybe that'll cause issues somewhere.

2021-11-30 10:52 UTC, dkarlovi commented on src/Composer/Command/ShowCommand.php
> +            $suggestions->suggestValues(array_merge(array_keys($rootPackage->getRequires()), array_keys($rootPackage->getDevRequires())));
Oh, sorry, I misread, I meant you mean to skip transient, not packagist. That one should definitely be filtered out on source, agreed. :+1:

2021-12-01 13:33 UTC, dkarlovi reviewed
Amazing work! :rocket:

2021-12-01 13:33 UTC, dkarlovi commented on src/Composer/Command/RequireCommand.php
> +        // @todo add ext-* ?
IMO no.

2021-12-01 13:33 UTC, dkarlovi commented on src/Composer/Command/BaseCommand.php
> +    protected function completePreferInstall(CompletionInput $input, CompletionSuggestions $suggestions)
`: bool`

2021-12-01 13:33 UTC, dkarlovi commented on src/Composer/Command/BaseCommand.php
> +    protected function completeInstalledPackage(CompletionInput $input, CompletionSuggestions $suggestions, $withPlatform = false)
`: bool`

2021-12-01 13:33 UTC, dkarlovi commented on src/Composer/Command/BaseCommand.php
> +    protected function completeAvailablePackage(CompletionInput $input, CompletionSuggestions $suggestions)
`: bool`

2021-12-01 13:33 UTC, dkarlovi commented on src/Composer/Command/BaseCommand.php
> +        $packages = $repos->search('^'.$input->getCompletionValue(), RepositoryInterface::SEARCH_NAME);
Does this require some sort of escaping since it contains a slash?

2021-12-01 13:37 UTC, Seldaek commented on src/Composer/Command/RequireCommand.php
> +        // @todo add ext-* ?
IMO yes? :) Why not?

2021-12-01 13:40 UTC, dkarlovi commented on src/Composer/Command/RequireCommand.php
> +        // @todo add ext-* ?
To be honest, it never even occurred to me you could `composer require ext-whatever`, I've never ever used that, I would usually add them manually, but now that I think about it some more, they're the same dependencies.

Do we have a canonical list of possible values?

2021-12-01 13:45 UTC, Seldaek commented on src/Composer/Command/RequireCommand.php
> +        // @todo add ext-* ?
Possible values no, but one can easily list what's available on the currently-running PHP from a PlatformRepository instance.

2021-12-01 13:47 UTC, Seldaek commented on src/Composer/Command/BaseCommand.php
> +        $packages = $repos->search('^'.$input->getCompletionValue(), RepositoryInterface::SEARCH_NAME);
slash isn't a special character, but running preg_quote on `$input->getCompletionValue()` would be safer I suppose.

2021-12-01 14:00 UTC, dkarlovi commented on src/Composer/Command/BaseCommand.php
> +        $packages = $repos->search('^'.$input->getCompletionValue(), RepositoryInterface::SEARCH_NAME);
@Seldaek how does that reflect here, the `search()` takes an already valid regex (including delimiters?) or does it construct one (in which it needs to `preg_quote7 with an already known delimiter).

2021-12-01 14:03 UTC, Seldaek commented on src/Composer/Command/BaseCommand.php
> +        $packages = $repos->search('^'.$input->getCompletionValue(), RepositoryInterface::SEARCH_NAME);
IMO the current usage is fine, but it should preg_quote the user input. Delimiters are then added in search() implementation, but delimiters are always `{`/`}` which are anyway escaped by preg_quote so it's safe.

2021-12-01 14:13 UTC, dkarlovi reviewed
Hands on experience.

2021-12-01 14:18 UTC, dkarlovi commented on src/Composer/Command/RequireCommand.php
> +        $this->completeAvailablePackage($input, $suggestions);
Note: this might be a good candidate for a second PR after this one is merged, we don't need to complete *all* the completions here because it might be a lot of work. This already sets a really nice groundwork.

2021-12-01 14:22 UTC, dkarlovi commented on src/Composer/Command/RequireCommand.php
> +        $this->completeAvailablePackage($input, $suggestions);
Another such example (a good "later" candidate) is suggesting values for the `config` command, I guess reading the [schema](https://getcomposer.org/schema.json) might be a way to do it?

2021-12-01 14:51 UTC, dkarlovi commented on src/Composer/Command/BaseCommand.php
> +        foreach (array_slice($packages, 0, 150) as $package) {
The fact that we're limiting to 150 here has non-obvious consequences when used, see #10325. This part needs some special attention to polish the UX here.

2021-12-01 15:32 UTC, GromNaN commented on src/Composer/Command/BaseCommand.php
> +    protected function completePreferInstall(CompletionInput $input, CompletionSuggestions $suggestions)
I sticked to PHP 5.3 features, but since the `complete` method has `:void` return type, PHP 7.1+ is required. I'll update my changes to use short-array syntax, arrow functions and return type.

2021-12-01 15:35 UTC, Seldaek commented on src/Composer/Command/BaseCommand.php
> +    protected function completePreferInstall(CompletionInput $input, CompletionSuggestions $suggestions)
Yeah once this gets merged we'll be requiring PHP 7.2+ so go for it :)

2021-12-01 15:36 UTC, dkarlovi commented on src/Composer/Command/BaseCommand.php
> +    protected function completePreferInstall(CompletionInput $input, CompletionSuggestions $suggestions)
Yeah, these changes are totally 5.3 incompatible already so no reason not to go all in.

2021-12-01 16:49 UTC, GromNaN commented on src/Composer/Command/RequireCommand.php
> +        // @todo add ext-* ?
I'm adding the completion on package when the input starts with `ext-`.

2022-01-03 11:53 UTC, Seldaek commented
Please rebase on latest main branch :)

2022-01-03 21:33 UTC, GromNaN commented
I rebased, fixed some phpstan warnings.

2022-01-03 21:34 UTC, GromNaN commented on src/Composer/Command/GlobalCommand.php
> +        }
Completion of subcommand is hard. I have this for beginning; but the global state of the application must be modified.
```php
        if ($application->has($command = $input->getArgument('command-name'))) {
            $input = CompletionInput::fromString(preg_replace(['{\bg(?:l(?:o(?:b(?:a(?:l)?)?)?)?)?\b}', '{|$}'], ['', ''], $input->__toString(), 1), 3);
            $command = $this->getApplication()->find($command);
            $input->bind($command->getDefinition());
            $this->getApplication()->resetComposer();
            $command->complete($input, $suggestions);
        }
```

2022-01-06 14:28 UTC, Seldaek commented on src/Composer/Command/GlobalCommand.php
> +        }
Not sure what you mean by "the global state of the application must be modified"?

2022-01-06 15:22 UTC, GromNaN commented on src/Composer/Command/GlobalCommand.php
> +        }
All the thinks that are done in the `run` method.
https://github.com/composer/composer/blob/5e4a8a882dc70398c3c53e7b3aabd16790c9e198/src/Composer/Command/GlobalCommand.php#L90-L116

That said ... that's not so complex.

2022-01-07 09:00 UTC, Seldaek commented on src/Composer/Command/GlobalCommand.php
> +        }
Ahh I see. Yes that should be easy to extract in a method to avoid duplication?

2022-01-24 14:58 UTC, GromNaN commented on src/Composer/Command/CreateProjectCommand.php
> +        $this->completeAvailablePackage($input, $suggestions) || $this->completePreferInstall($input, $suggestions);
I'm not 100% satisfied by this code syntax. It would be more decoupled if completion callback were attached to each argument/option #44948.

2022-03-18 10:18 UTC, Seldaek commented on src/Composer/Package/Version/VersionGuesser.php
> +        }
Should do a similar bypass to get rid of https://github.com/composer/composer/blob/bbf2e94579cb91f8eacb9bd050f4b13aef67a853/src/Composer/Factory.php#L304-L317 

And I guess move this condition above to `Platform::isBashCompletionProcess()` or something so we avoid duplicating it.

2022-04-15 11:56 UTC, GromNaN commented on src/Composer/Package/Version/VersionGuesser.php
> +        }
`Platform::isInputCompletionProcess()` added.

2022-05-12 14:15 UTC, Seldaek commented on src/Composer/Command/GlobalCommand.php
> +        }
See https://github.com/composer/composer/pull/10320/commits/dd2e2d7e26d2698883960ee7dccda705ae89182e - I tried doing it but it doesn't seem to work, I think I missed something, perhaps you can have a look?

2022-05-12 14:16 UTC, Seldaek commented on src/Composer/Command/CompletionTrait.php
> +            if (!str_starts_with($input->getCompletionValue(), 'ext-')) {
I'll try and take care of improving this method and suggestAvailablePackage together with taking a look at performance tomorrow, please leave it alone for now.

2022-05-12 14:16 UTC, stof commented on src/Composer/Command/CompletionTrait.php
> +            if (!str_starts_with($input->getCompletionValue(), 'ext-')) {
> Do you have more details about `lib-*`? I've never seen such packages.

Look in the PlatformRepository

> This vendor prefix could be prohibed?

I don't see any reason for that. There is no conflicts between such packages and platform packages (as such packages will always have a `/` and platform packages don't have it).
Forbidding such prefixes (making existing packages unusable) just for lazyness of merging 2 lists in the completion suggestions looks wrong to me.

2022-05-12 14:17 UTC, stof commented on src/Composer/Factory.php
> +        if (!Platform::isInputCompletionProcess()) {
should the `!` be removed here ?

2022-05-12 18:53 UTC, Seldaek commented on src/Composer/Factory.php
> +        if (!Platform::isInputCompletionProcess()) {
Oops yes thanks.

2022-05-12 21:14 UTC, Seldaek commented on src/Composer/Command/CompletionTrait.php
> +            if (!str_starts_with($input->getCompletionValue(), 'ext-')) {
OK pushed a bunch of fine-tuning and improvements, IMO the package completion is now working well enough that it's usable.

2022-05-13 07:28 UTC, Seldaek commented on src/Composer/Command/BaseCommand.php
> +        foreach (array_slice($packages, 0, 150) as $package) {
I did improve this in https://github.com/composer/composer/pull/10320/commits/55dc80862ea81748df77153fdf14f861759c68b3 - for vendor names though when going through packagist.org results there are still so many that it's kind of a mess and you'll in most cases have to type enough of what you want to get it, but then it completes packages names within the vendor which is already quite useful IMO.

2022-05-13 08:51 UTC, Seldaek commented
OK PR is good to merge for me now except for the glitches in the global command. @GromNaN do you think you have time to look at that soon? Otherwise I'd probably merge as is and it can be done in a follow-up PR.

2022-05-16 20:46 UTC, GromNaN commented
> OK PR is good to merge for me now except for the glitches in the global command. @GromNaN do you think you have time to look at that soon? Otherwise I'd probably merge as is and it can be done in a follow-up PR.

Completion on `global` command needs some hooks in the `Composer\Console\Application`. I don't have anything conclusive ATM. Better work on it in a separate PR.

2022-05-16 20:49 UTC, GromNaN commented
Next step will be the setup the completion script with composer.phar.
This line may be removed.
https://github.com/composer/composer/blob/575fbfb53fcc2388916d554271c99c8281fea782/src/Composer/Compiler.php#L123

2022-06-01 19:59 UTC, merged