Allow using temporary update constraints on all packages (incl non-root)
composer/composer pull request #10773
Opened 2022-05-12 12:18 UTC by Seldaek

Fixes #10436

2022-05-12 12:41 UTC, stof requested changes

2022-05-12 12:41 UTC, stof commented on src/Composer/Command/UpdateCommand.php
> +        $rootPackage->setTemporaryConstraints($temporaryConstraints);
shouldn't the temporary constraints be added in the installer rather than in the root package ?

2022-05-12 12:41 UTC, stof commented on src/Composer/DependencyResolver/PoolBuilder.php
>                          unset($this->packages[$index]);
shouldn't the unsetting be done separately for each package depending on whether it matches or no ?

2022-05-12 12:41 UTC, stof commented on src/Composer/DependencyResolver/Problem.php
> +                    return array("- Root composer.json requires $packageName".self::constraintToText($constraint) . ', ', 'found '.self::getPackageList($packages, $isVerbose, $pool, $constraint).' bu
temporary constraints are not about the root composer.json, but about the command arguments.

2022-05-13 14:02 UTC, Seldaek commented on src/Composer/DependencyResolver/PoolBuilder.php
>                          unset($this->packages[$index]);
I am not sure.. the package and its aliases are usually connected and have to be all installed or none. So here we keep the whole group if any of the aliased or alias matches the constraint, and if none match the whole thing is removed. I think this is correct.

2022-05-13 14:03 UTC, Seldaek commented on src/Composer/DependencyResolver/Problem.php
> +                    return array("- Root composer.json requires $packageName".self::constraintToText($constraint) . ', ', 'found '.self::getPackageList($packages, $isVerbose, $pool, $constraint).' bu
The "root composer.json" part is about the require/constraint which caused the problem, not about the temporary constraint, this is correct as is (but slightly obscure code to be fair).

2022-05-13 14:04 UTC, Seldaek commented on src/Composer/Command/UpdateCommand.php
> +        $rootPackage->setTemporaryConstraints($temporaryConstraints);
Yup that probably makes more sense I'll update.

2022-05-13 14:25 UTC, stof commented on src/Composer/DependencyResolver/Problem.php
> +                    return array("- Root composer.json requires $packageName".self::constraintToText($constraint) . ', ', 'found '.self::getPackageList($packages, $isVerbose, $pool, $constraint).' bu
Then, can you add a test showing what happens when a temporary constraint causes a conflict on a transitive dependency ?

2022-05-27 12:51 UTC, merged