Add audit command to check for security issues [WIP]
composer/composer pull request #10798
Opened 2022-05-24 09:53 UTC by GuySartorelli

Closes #10329

## Description
Adds an audit command which checks for security vulnerability advisories for installed packages using [the API on packagist.org](https://packagist.org/apidoc#list-security-advisories).

## Things the audit task currently does not do:
- Confirm the packages in `vendor` dir match what `composer.lock` says they should be
- In the event packages in `vendor` dir don't match `composer.lock`, check for advisories for those
- If composer.lock is missing, check for advisories based on the constraints in the `composer.json` file

## Other things that still need to be added to this PR
- Optional auditing on some pre-existing commands
  - `update`
  - `install`
  - `require`
- Documentation once those commands have auditing added
- Test coverage

## Problems
A project with even a relatively small number packages will get a 502 response from pacakgist.
> The "https://packagist.org/api/security-advisories?packages[]=`ommitted for brevity`" file could not be downloaded (HTTP/2 502 )

I also got the 502 error when trying the query in the browser. This seems to be caused by too many packages in a single request; if I significantly reduce the number of packages in the query, it returns an appropriate response. This is a major blocker for this functionality being implemented, so if someone knows a way around this, please let me know.

2022-05-24 09:56 UTC, stof commented
> I also got the 502 error when trying the query in the browser. This seems to be caused by too many packages in a single request; if I significantly reduce the number of packages in the query, it returns an appropriate response. This is a major blocker for this functionality being implemented, so if someone knows a way around this, please let me know.

Well, one thing you could do is splitting the list of packages into batches (the batch size should be chosen based on the supported size for the Packagist API) and send multiple requests. Thanks to the parallelization support in Composer 2+, you can even send those requests in parallel.

2022-05-24 10:05 UTC, GuySartorelli commented
That's a good idea - I couldn't find any information about what the limit actually is but I'll have another look, and failing that I can always do some trial and error to find it. Bonus points for anyone who can point me in the right direction or who already knows what the limit is.

2022-05-24 12:40 UTC, Seldaek commented
Yes IMO putting the package list in the POST body will fix this as this is AFAIK not size limited at all, unlike URL length which has limits in various places.

2022-05-26 09:27 UTC, GuySartorelli commented
Currently blocked because the packagist API returns a 404 error on POST requests. I've created an issue for it under composer/packagist#1309

2022-05-26 10:12 UTC, GuySartorelli commented
The basic functionality is working now - any review on the `AuditCommand` or `Auditor` and related documentation would be useful at this stage.

2022-05-26 10:55 UTC, GuySartorelli commented
It looks like there's some PHPStan issues as well - to be honest I don't understand what I need to do to resolve those. A lot of the errors are saying the new command doesn't define some options... but it doesn't need those options.

2022-05-30 08:20 UTC, GuySartorelli commented
I've resolved some of the PHPStan issues. The ones that I think are false alarms I've tried to add to the baseline, but it doesn't seem to have taken. There are a couple of PHPStan issues there as well which are unrelated to this PR.

2022-06-03 14:58 UTC, GuySartorelli commented
This is now ready to be reviewed.

2022-06-03 19:00 UTC, Seldaek commented
Thanks - sorry I've had a rough few weeks here so lagging behind on many things and it may take me a bit longer to get to this, but regarding phpstan if you're still having issues just ignore them that's no biggie for now.

2022-06-03 20:04 UTC, herndlm commented on src/Composer/Command/AuditCommand.php
> +    protected function configure()
I saw other commands use `void` as return type here, that should get rid of one of the phpstan errors

2022-06-03 23:38 UTC, GuySartorelli commented
@Seldaek No worries, there's no rush. 

@herndlm interesting! I didn't think I could add a return type there because it wouldn't match the signature of the symfony command class's configure method - but you're right, other commands here have added it. I'll make that change. 
https://github.com/symfony/console/blob/c9646197ef43b0e2ff44af61e7f0571526fd4170/Command/Command.php#L198

2022-06-04 03:33 UTC, GuySartorelli commented on src/Composer/Util/Auditor.php
> +        if (count($packages) > 0 && $filterByVersion) {
```suggestion
        if (count(advisories) > 0 && $filterByVersion) {
```
Oops. I put the wrong variable here. I'll make this change once people have been given a chance to review the or as a whole.

2022-06-06 11:22 UTC, Seldaek requested changes
Thanks, overall it look good I think! Lots of comments but a lot is for minor code tweaks.

2022-06-06 11:22 UTC, Seldaek commented on src/Composer/Util/Auditor.php
> +                        '<fg=red>Reported at</>',
I think I'd remove the red text hre and in the plain output. It doesn't seem to add a lot of value and I'd argue it even highlights the wrong thing as the headings aren't the most important thing here.

2022-06-06 11:22 UTC, Seldaek commented on src/Composer/Util/Auditor.php
> +        }
I'd add a `summary` format which only outputs `there are X installed packages with known vulnerabilities, run composer audit to see them`. I suspect we may not want to spam with the full output on every update/install.

2022-06-06 11:22 UTC, Seldaek commented on src/Composer/Installer.php
> +            $packages = $this->locker->getLockedRepository($this->devMode)->getPackages();
Rather use `$localRepo->getCanonicalPackages()` here I think, so it checks all installed packages, not what's in the lock file, although at this point it should be the same, it's semantically more accurate IMO.

2022-06-06 11:22 UTC, Seldaek commented on src/Composer/Command/AuditCommand.php
> +        $httpDownloader = Factory::createHttpDownloader($this->getIO(), $composer->getConfig());
```suggestion
        $httpDownloader = $composer->getLoop()->getHttpDownloader();
```

2022-06-06 11:22 UTC, Seldaek commented on src/Composer/Command/AuditCommand.php
> +        $packages = $locker->getLockedRepository(!$input->getOption('no-dev'))->getPackages();
It'd be preferable/more consistent IMO to do something like https://github.com/composer/composer/blob/main/src/Composer/Command/ShowCommand.php#L234-L259 with a --locked flag to optionally read from lock file, but by default it should read from the local (installed) repository.

2022-06-06 11:24 UTC, Seldaek commented on src/Composer/Util/Auditor.php
> +        if (count($packages) > 0 && $filterByVersion) {
@GuySartorelli please append new commits for new changes, it's much easier to do further reviews. I can squash when merging if it turns into a huge mess.

2022-06-06 21:37 UTC, GromNaN commented on src/Composer/Command/AuditCommand.php
> +                new InputOption('format', 'f', InputOption::VALUE_OPTIONAL, 'Output format. Must be "table" or "plain".', Auditor::FORMAT_TABLE),
Other commands use `text` instead of `plain`.

You should use `Composer\Console\Input\InputOption` to suggest values in bash completion. See the LicenseCommand if you need an example.

2022-06-06 21:49 UTC, GuySartorelli commented on src/Composer/Command/AuditCommand.php
> +                new InputOption('format', 'f', InputOption::VALUE_OPTIONAL, 'Output format. Must be "table" or "plain".', Auditor::FORMAT_TABLE),
"table" and "plain" are both text formats - In `LicencesCommand` I take "text" to be as opposed to "json" i.e. it's not just a layout format difference, it's a difference between plain text and a JSON formatting of data.
I can change "plain" to "text" if there is a push for that, but I think in this situation "plain" probably makes more sense.

I will make the change to aid bash completion though.

2022-06-06 21:51 UTC, GuySartorelli commented on src/Composer/Util/Auditor.php
> +        }
Good idea.
1. Should "summary" be the default format for all commands other than `audit` itself?
2. Should the "summary" format also be available from `composer audit` itself? It might be a bit odd to run `composer audit --format=summary` and have it tell you to run `composer audit` - but at the same time, if someone intentionally selects the summary format maybe that is expected?

2022-06-06 21:53 UTC, GuySartorelli commented on src/Composer/Util/Auditor.php
> +                $content['packages'][] = $package->getName();
That sounds like a good idea - though I don't know what that would look like as far as how that information is passed to the API...
In either case I don't think that's critical to this functionality. If the packagist API gets updated to accept version numbers I'll be happy to update this, but that can always be done as an enhancement later on as well.

2022-06-06 21:56 UTC, GuySartorelli commented on src/Composer/Installer.php
> +                $this->io->writeError('No packages - skipping audit.');
I added this because users may be expecting some audit message (either "no issues" or "found x issues") - but if there are no packages, there will be no audit message. That may seem like something went wrong rather than an intentional lack of messaging.

I'm happy to remove this if with this context you still feel it's not needed.

2022-06-07 09:58 UTC, Seldaek commented on src/Composer/Installer.php
> +                $this->io->writeError('No packages - skipping audit.');
Ok let's leave it in for now, we'll see with day to day usage if it gets too noisy.

2022-06-07 09:58 UTC, Seldaek commented on src/Composer/Util/Auditor.php
> +                $content['packages'][] = $package->getName();
Absolutely, feel free to keep it as is for now. I'll take a look at the packagist side whenever.

2022-06-07 09:59 UTC, Seldaek commented on src/Composer/Util/Auditor.php
> +        }
1. I'd say summary should be default yes, except audit cmd probably using table as default?
2. Yeah not such a big deal :)

2022-06-08 08:20 UTC, GuySartorelli commented on src/Composer/Util/Auditor.php
> +        if (count($packages) > 0 && $filterByVersion) {
Will do

2022-06-08 08:30 UTC, GuySartorelli commented on src/Composer/Command/CreateProjectCommand.php
> +                new InputOption('audit-format', null, InputOption::VALUE_OPTIONAL, 'Audit output format. Must be "table" or "plain".', Auditor::FORMAT_TABLE),
I'll add a new const array to hold all formats on the `Auditor` class and pass that in here instead - that way any changes to the formats just need to be updated in that one place.

2022-06-08 08:34 UTC, GuySartorelli commented on src/Composer/Util/Auditor.php
> +        if (!in_array($format, [self::FORMAT_TABLE, self::FORMAT_PLAIN])) {
I'll make this change, but I don't think in this case it makes a difference.

2022-06-08 08:35 UTC, Seldaek commented on src/Composer/Util/Auditor.php
> +        if (!in_array($format, [self::FORMAT_TABLE, self::FORMAT_PLAIN])) {
It doesn't, but our phpstan config enforces strict mode to avoid surprises.

2022-06-08 08:59 UTC, glaubinix commented on src/Composer/Util/Auditor.php
> +                $content['packages'][] = $package->getName();
I wonder whether instead of or in addition to sending versions, storing the response in the Composer cache and sending a `if-modified since` header wouldn't be a better option? Advisories do not change that often and on CI you will run several composer installs that could reuse the cache file.

2022-06-08 09:11 UTC, GuySartorelli commented on src/Composer/Util/Auditor.php
> +                $content['packages'][] = $package->getName();
I don't know enough about cache to even begin implementing that - especially since it's not only the advisories that might change but the installed packages as well. I'm happy for someone else to implement that improvement after this PR has been merged, but it is not something I feel confident tackling.

2022-06-08 09:16 UTC, GuySartorelli commented on src/Composer/Command/AuditCommand.php
> +        $packages = $locker->getLockedRepository(!$input->getOption('no-dev'))->getPackages();
Looks that that uses a method [`filterRequiredPackages()`](https://github.com/composer/composer/blob/e9b44b449945dd7ac614c759240bb25f0617a38d/src/Composer/Command/ShowCommand.php#L1418) to filter out the dev dependencies, which is remarkably similar to [`LicensesCommand::filterRequiredPackages()`](https://github.com/composer/composer/blob/e9b44b449945dd7ac614c759240bb25f0617a38d/src/Composer/Command/LicensesCommand.php#L163).

I really don't want to add a _third_ implementation of this method, but I'm not sure where the method should exist so that it can be shared across commands. Do you have any preference? My current thinking is to just put it into `BaseCommand`.

2022-06-08 09:29 UTC, GuySartorelli commented on src/Composer/Command/AuditCommand.php
> +        $packages = $locker->getLockedRepository(!$input->getOption('no-dev'))->getPackages();
I've duplicated it for now, just so that the functionality is available in `AuditCommand` - but it's obviously not ideal having such unDRY code.

2022-06-08 09:45 UTC, GuySartorelli commented
Requested changes have been made.

2022-06-08 11:26 UTC, GuySartorelli commented on src/Composer/Util/Auditor.php
> +    public function __construct(HttpDownloader $httpDownloader, string $format = self::FORMAT_TABLE)
Just giving this another once-over... I wonder if I should remove the format parameter from the constructor? It wouldn't make sense for someone who is using this class for its `getAdvisories()` method to need to think at all about the format of `audit()` output... 🤔

2022-06-08 11:32 UTC, Seldaek commented on src/Composer/Util/Auditor.php
> +    public function __construct(HttpDownloader $httpDownloader, string $format = self::FORMAT_TABLE)
Yes having that param in audit() probably makes more sense :)

2022-06-08 11:43 UTC, GuySartorelli commented on src/Composer/Util/Auditor.php
> +    public function __construct(HttpDownloader $httpDownloader, string $format = self::FORMAT_TABLE)
Sweet. I've made that change.

2022-06-10 22:39 UTC, ktomk commented
For the output format could JSON Text be a other variant? I've seen there is a table, so perhaps some very straight forward JSON Array of JSON Objects could be nice to pass along to further (automated) processing.

2022-06-10 23:54 UTC, GuySartorelli commented
@ktomk At this stage I'd just be keen to see the feature merged - that sounds like an enhancement that can be added after the fact quite easily if there is real world use for it. I'd be quite happy for someone to create a follow-up PR with that format if there is a need for it but it's not something I want to add to this PR right now.

2022-06-12 10:46 UTC, Seldaek approved these changes
Thanks, looking good I think now, a couple typos/nitpicks and then it's mergeable I think.

2022-06-12 10:46 UTC, Seldaek commented on doc/03-cli.md
> +* **--audit-format:** Audit output format. Must be "table", "plain", or "summary" (default)..
```suggestion
* **--audit-format:** Audit output format. Must be "table", "plain", or "summary" (default).
```

2022-06-12 10:46 UTC, Seldaek commented on doc/03-cli.md
> +* **--audit-format:** Audit output format. Must be "table", "plain", or "summary" (default)..
```suggestion
* **--audit-format:** Audit output format. Must be "table", "plain", or "summary" (default).
```

2022-06-12 10:46 UTC, Seldaek commented on doc/03-cli.md
> +* **--audit-format:** Audit output format. Must be "table", "plain", or "summary" (default)..
```suggestion
* **--audit-format:** Audit output format. Must be "table", "plain", or "summary" (default).
```

2022-06-12 10:46 UTC, Seldaek commented on doc/03-cli.md
> +* **--audit-format:** Audit output format. Must be "table", "plain", or "summary" (default)..
```suggestion
* **--audit-format:** Audit output format. Must be "table", "plain", or "summary" (default).
```

2022-06-12 10:46 UTC, Seldaek commented on src/Composer/Installer.php
> +                    $this->io->error('Error occurred while auditing locked packages.');
```suggestion
                    $this->io->error('Failed to audit installed packages.');
```

2022-06-12 10:46 UTC, Seldaek commented on src/Composer/Util/Auditor.php
> +    public const API_URL = 'https://packagist.org/api/security-advisories/';
```suggestion
    private const API_URL = 'https://packagist.org/api/security-advisories/';
```

2022-06-12 10:46 UTC, Seldaek commented on src/Composer/Command/AuditCommand.php
> +        $composer = $this->requireComposer($input->getOption('no-plugins'), $input->getOption('no-scripts'));
No need to forward those they are used as default value already for conciseness

```suggestion
        $composer = $this->requireComposer();
```

2022-06-12 10:46 UTC, Seldaek commented on src/Composer/Command/AuditCommand.php
> +                throw new \UnexpectedValueException('Valid composer.json and composer.lock files is required to run this command with --locked');
```suggestion
                throw new \UnexpectedValueException('Valid composer.json and composer.lock files are required to run this command with --locked');
```

2022-06-12 10:48 UTC, Seldaek commented on src/Composer/Command/AuditCommand.php
> +                new InputOption('format', 'f', InputOption::VALUE_OPTIONAL, 'Output format. Must be "table", "plain", or "summary".', Auditor::FORMAT_TABLE),
```suggestion
                new InputOption('format', 'f', InputOption::VALUE_REQUIRED, 'Output format. Must be "table", "plain", or "summary".', Auditor::FORMAT_TABLE),
```

2022-06-12 10:53 UTC, Seldaek commented on src/Composer/Util/Auditor.php
> +class Auditor
```suggestion
/**
 * @internal
 */
class Auditor
```

2022-06-12 10:53 UTC, Seldaek commented on src/Composer/Command/AuditCommand.php
> +        $packages = $locker->getLockedRepository(!$input->getOption('no-dev'))->getPackages();
Yeah this is fine, I made a note to clean this up later :)

2022-06-12 11:09 UTC, GuySartorelli commented on src/Composer/Util/Auditor.php
> +class Auditor
I don't see any reason to mark this as internal. Part of the reason I wanted to do this was so that this functionality _can_ be used in other projects. It's also why the `getAdvisories()` method is public and why it includes functionality not used but `AuditCommand`.

2022-06-12 13:14 UTC, Seldaek commented on src/Composer/Util/Auditor.php
> +class Auditor
Yeah I am a bit overly paranoid about promising BC these days because a v3 is not around the corner..

If the point is reuse I'd argue we should later (once stabilized) publish this as a standalone lib because people depending on the whole of composer/composer is usually a bad idea..

2022-06-12 21:12 UTC, GuySartorelli commented on src/Composer/Util/Auditor.php
> +class Auditor
I'm okay with that approach.

2022-06-12 23:30 UTC, GuySartorelli commented
Requested changes have been made.

2022-06-12 23:38 UTC, GuySartorelli commented
Tests fixed

2022-06-22 14:00 UTC, Seldaek commented
Thanks! Merged as d93239ddd9e6c18a2f7db3cdf94213dd892fa950 and fixed up some remaining issues in 611b21589 🥳

2022-06-22 14:00 UTC, closed without merging

2022-06-23 05:50 UTC, Seldaek commented
The more I think of it the more I think we can't really extract this, as it'll probably need to be integrated deeper into the Repository code than it is now. 

I think the better way would be to publish a packagist.org API client library really, that would be completely separate from Composer, and would not require Package objects or anything to function.

2022-06-23 06:41 UTC, GuySartorelli commented
That's fair. I'd be happy to do development work on such a library with as much or as little guidance as you want to provide. While I could implement such a library in some arbitrary repo it makes sense to me that there would be such a repository under the composer organisation which people can just add to their dependencies when and as they need it.

2022-06-23 08:31 UTC, stof commented
You mean something like https://packagist.org/packages/knplabs/packagist-api ?

2022-06-23 10:15 UTC, Seldaek commented
Ah yes there's that, then maybe worth sending a PR there porting the Auditor querying bits @GuySartorelli if you feel like it?

2022-06-23 10:24 UTC, GuySartorelli commented
I'll take a look - I wasn't aware of that package. Still doesn't feel as appropriate as having one in GitHub.com/composer but I won't push for that if the appetite for creating it isnt here 😅

2022-07-23 10:54 UTC, barryvdh commented
> For the output format could JSON Text be another variant? I've seen there is a table, so perhaps some very straight forward JSON Array of JSON Objects could be nice to pass along to further (automated) processing.

I created a follow-up PR for the json format here: https://github.com/composer/composer/pull/10965