test: Create test for CheckPlatformReqsCommand
composer/composer pull request #10932
Opened 2022-07-09 18:45 UTC by theoboldalex

Created a test for the CheckPlatformReqsCommand which increases coverage from 8% to 76%.

2022-07-15 11:34 UTC, Seldaek requested changes

2022-07-15 11:34 UTC, Seldaek commented on tests/Composer/Test/Command/CheckPlatformReqsCommandTest.php
> +        ];
This is good to have but would be great to verify the behavior actually works by creating some packages and checking the output matches expected output.

See TestCase::initTempComposer, createInstalledJson  and createComposerLock for this. https://github.com/composer/composer/blob/70f2dd6eddd5916f70b3d73dd3170a3d2d3a7681/tests/Composer/Test/Command/BumpCommandTest.php#L28-L47 also has a real example of using these.

2022-07-15 11:34 UTC, Seldaek commented on tests/Composer/Test/Command/CheckPlatformReqsCommandTest.php
> +        ];
As above, would be nice to check this actually does something and not just runs without failing.

2022-07-15 11:36 UTC, Seldaek commented
Thanks for getting started here. This definitely is better than nothing as it runs the code and would catch any critical error, but it'd be cool if you find time to go further and actually check the output. See this example too for inspiration on checking output https://github.com/composer/composer/blob/70f2dd6eddd5916f70b3d73dd3170a3d2d3a7681/tests/Composer/Test/Command/UpdateCommandTest.php#L31

2022-07-15 13:43 UTC, theoboldalex commented
Thanks for the feedback. I'll get to work on the requested changes.

2022-09-14 02:25 UTC, jeffwidman commented
Gentle nudge @theoboldalex be great to see this move forward

2022-10-14 19:56 UTC, theoboldalex commented
Apologies for the delay on getting back to this. I have actioned the points raised by @Seldaek so this is ready for another review. Thanks

2022-10-25 14:56 UTC, Seldaek approved these changes
Looks good now, just a couple style nitpicks

2022-10-25 14:57 UTC, Seldaek commented
Thanks!

2022-10-25 17:05 UTC, theoboldalex commented
I have actioned the code style fixes as requested.

2022-10-25 17:42 UTC, merged