Add json format to Audit command
composer/composer pull request #10965
Opened 2022-07-23 10:53 UTC by barryvdh

Follow up on #10798 and #10898, as suggested in https://github.com/composer/composer/pull/10798#issuecomment-1152782931

This adds a `format=json` option to the command, to allow for. Currently in the same format it already is (because why not?). In the 'advisories' object, so a summary or the list of packages can still be added later if required. So grouped by package:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/973269/180602047-b64c265d-030e-4a36-8e49-c96f4d63d6cd.png">

No actual real-life use case for this, except for opening the possibility to process it during a pipeline/action (and perhaps suggest updates or format an advisory yourself)

2022-07-23 10:58 UTC, Seldaek approved these changes

2022-07-23 10:58 UTC, Seldaek commented on src/Composer/Command/AuditCommand.php
> +                new InputOption('format', 'f', InputOption::VALUE_REQUIRED, 'Output format. Must be "table", "plain", "json" or "summary".', Auditor::FORMAT_TABLE, Auditor::FORMATS),
Thanks, looks good I think! just one comment can you please update the other Input Option in other commands (look for audit-format) as well as the 04-cli.md docs to make sure the json format is listed everywhere?

2022-07-23 11:04 UTC, barryvdh commented on src/Composer/Command/AuditCommand.php
> +                new InputOption('format', 'f', InputOption::VALUE_REQUIRED, 'Output format. Must be "table", "plain", "json" or "summary".', Auditor::FORMAT_TABLE, Auditor::FORMATS),
Yes updated!

2022-07-23 11:05 UTC, GuySartorelli commented on src/Composer/Advisory/Auditor.php
> +            $io->write(JsonFile::encode(['advisories' => $advisories]));
Why add the "advisories" key, as opposed to just encoding the array as is?

2022-07-23 11:06 UTC, GuySartorelli requested changes

2022-07-23 11:06 UTC, GuySartorelli commented on src/Composer/Advisory/Auditor.php
> +        if (self::FORMAT_JSON === $format) {
This should me moved into `outputAdvisories()` with the other format outputs.

2022-07-23 11:06 UTC, barryvdh commented on src/Composer/Advisory/Auditor.php
> +            $io->write(JsonFile::encode(['advisories' => $advisories]));
I think that is more clear. And also leaves the option to add any other (meta) data like summary/number of errors/list of packages later.

2022-07-23 11:09 UTC, barryvdh commented on src/Composer/Advisory/Auditor.php
> +        if (self::FORMAT_JSON === $format) {
I originally did that, but I think this was clearer in the end, because the section below also writes the error summary (good or bad) and I don't think you want that  (even though it's in the error output). And that output is only written when there are advisories, I think it's clearer that there is always the advisories array, even when empty.

2022-07-23 11:10 UTC, GuySartorelli commented on src/Composer/Advisory/Auditor.php
> +        if (self::FORMAT_JSON === $format) {
The "found x advisories" could (probably should) also be moved into the output method, and only be done for the nonhjson formats.

2022-07-23 11:13 UTC, barryvdh commented
I've updated the docs and audit-format command. Not sure why CI is failing on 7.3 only. It looks a bit random?

2022-07-23 11:21 UTC, Seldaek commented
Yeah sorry that's a temporary failure because we're on a dev version of symfony console, ignore it.

2022-07-23 11:28 UTC, barryvdh commented on src/Composer/Advisory/Auditor.php
> +        if (self::FORMAT_JSON === $format) {
Okay, I'll let @Seldaek decide on this. What do you prefer?

2022-07-23 12:59 UTC, Seldaek commented on src/Composer/Advisory/Auditor.php
> +        if (self::FORMAT_JSON === $format) {
I don't have a super strong opinion either way. It's all private code so can be refactored later if really needed. As such I think it's good enough as is.

2022-07-25 11:13 UTC, merged

2022-07-25 11:13 UTC, Seldaek commented
Thanks again