PHPStan: Fixed handling of union types in ConfigReturnTypeExtension
composer/composer pull request #11312
Opened 2023-02-09 16:21 UTC by staabm

see https://phpstan.org/blog/why-is-instanceof-type-wrong-and-getting-deprecated

2023-02-09 16:22 UTC, staabm commented on src/Composer/PHPStan/ConfigReturnTypeExtension.php
> +        $strings = TypeUtils::getConstantStrings($keyType);
refactored to use the deprecated `TypeUtils::getConstantStrings` method, since composer itself does not specify a min-phpstan version requirement.

2023-02-09 16:28 UTC, stof requested changes

2023-02-09 16:28 UTC, stof commented on src/Composer/PHPStan/ConfigReturnTypeExtension.php
> +                if (isset($this->properties[$string->getValue()])) {
Any string not being known here should force skipping the more precise type, falling back to the basic method signature

2023-02-09 16:33 UTC, staabm commented on src/Composer/PHPStan/ConfigReturnTypeExtension.php
> +        // for compat with old phpstan versions, we use a deprecated phpstan method.
good point, fixed

2023-02-09 16:34 UTC, staabm commented on src/Composer/PHPStan/ConfigReturnTypeExtension.php
> +        $defaultReturn = ParametersAcceptorSelector::selectSingle($methodReflection->getVariants())->getReturnType();
in case we would have a min phpstan version of 1.5.0 or higher, the method could just return null and the [phpstan-core would take care of determining the default-return type.](https://github.com/phpstan/phpstan-src/commit/a897d3a4a0bc1cc8a385eab34da399a75969a538)

2023-02-10 12:53 UTC, Seldaek commented on src/Composer/PHPStan/ConfigReturnTypeExtension.php
> +        $defaultReturn = ParametersAcceptorSelector::selectSingle($methodReflection->getVariants())->getReturnType();
Feel free to assume latest PHPStan and bump the require if you like :)

2023-02-10 12:56 UTC, staabm commented on src/Composer/PHPStan/ConfigReturnTypeExtension.php
> +        $defaultReturn = ParametersAcceptorSelector::selectSingle($methodReflection->getVariants())->getReturnType();
this won't work. it depends on the phpstan version used by the project which depends on composer.

the extension is meant for re-use in plugin projects. this means I would either need to declare a non-dev dependency on phpstan or add a conflict. both things I don't like.

2023-02-10 12:57 UTC, Seldaek commented on src/Composer/PHPStan/ConfigReturnTypeExtension.php
> +        $defaultReturn = ParametersAcceptorSelector::selectSingle($methodReflection->getVariants())->getReturnType();
Oh right I forgot that aspect, let's leave as is then 👍🏻

2023-02-10 13:00 UTC, merged