Add access token authentication for Bitbucket repositories
composer/composer pull request #11501
Opened 2023-06-09 06:29 UTC by BernhardK91

This PR adds access token authentication for Bitbucket repositories.

## Background

Composer already supports Bitbucket authentication with OAuth. Bitbucket's OAuth configuration has some down sites. Because the OAuth token is configured at workspace levels, it applies to all repositories in that workspace. 

To have repository-based tokens, Bitbucket provides so-called "Access tokens", that can be found in the repository settings:

![image](https://github.com/composer/composer/assets/5526334/078c56fe-2a88-45ad-b8d5-77843ba26f96)

## Configuration

This PR adds a new parameter to the repository's configuration. A Bitbucket repository that uses access token authentication can be configured as followed in the `composer.json` file:

```
[...]
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.backpackforlaravel.com/"
        },
        {
            "type": "bitbucket",
            "url": "https://bitbucket.org/{workspace}/{repository-name}.git",
            "access-token": "{access token goes here}"
        }
    ],
[...]
```

This will add the access token to the `composer.json`. Normally, access tokens should never be committed, but in this case, in my opinion, this is a little bit different. The token applies only to that one single repositories and (mostly) would be set up with only reading rights. So, who has access to the code base of the project will most likely have access to the used repository.

## Conclusion

This is my first PR for composer. So please let me know if I missed anything or if you have any concerns about this change. Thank you!

2023-06-10 07:08 UTC, cafferata commented
Something I could think of: Completing the documentation with this feature. See`bitbucket-oauth`:
1. https://getcomposer.org/doc/06-config.md#bitbucket-oauth
1. https://getcomposer.org/doc/articles/authentication-for-private-packages.md#bitbucket-oauth

2023-06-10 21:57 UTC, BernhardK91 commented
@cafferata Thank you for your response and mentioning updating the documentation. While going through that, I also figured out a better way of adding the access token that is more in line with the other authentication options. 
In addition, I found a couple of more issues of the original PR and fixed them as well. 

Looking forward to more feedback. :-)

2023-06-10 22:09 UTC, cafferata requested changes

2023-06-10 22:09 UTC, cafferata commented on doc/articles/authentication-for-private-packages.md
> +|[bitbucket-oauth](#bitbucket-oauth)|no|
@BernhardK91 I guess you mean `bitbucket-token`?

```suggestion
|[bitbucket-token](#bitbucket-token)|no|
```

2023-06-10 22:10 UTC, cafferata commented
Your welcome! I'll check it later 👍

2023-06-10 22:18 UTC, BernhardK91 commented on doc/articles/authentication-for-private-packages.md
> +|[bitbucket-oauth](#bitbucket-oauth)|no|
Ouh yeah. I missed that. Thank you!

2023-06-13 11:09 UTC, cafferata requested changes
I think after reading the documentation it's a clear story. Just minor feedback points. I leave the technical code review to @Seldaek.

2023-06-13 11:09 UTC, cafferata commented on doc/articles/authentication-for-private-packages.md
> +The BitBucket driver is also able to access your private repositories via the BitBucket REST APIs, using (Bitbucket Repository Access Tokens)[https://support.atlassian.com/bitbucket-cloud/docs/create
(Multiple) small typo in de `Bitbucket` name.

```suggestion
The Bitbucket driver is also able to access your private repositories via the Bitbucket REST APIs, using (Bitbucket Repository Access Tokens)[https://support.atlassian.com/bitbucket-cloud/docs/create-a-repository-access-token/].
```

2023-06-13 11:09 UTC, cafferata commented on doc/articles/authentication-for-private-packages.md
> +The BitBucket driver is also able to access your private repositories via the BitBucket REST APIs, using (Bitbucket Repository Access Tokens)[https://support.atlassian.com/bitbucket-cloud/docs/create
Here too I suspect that the link is desired to be clickable. For this, the Markdown syntax must be reversed.

```suggestion
The BitBucket driver is also able to access your private repositories via the BitBucket REST APIs, using [Bitbucket Repository Access Tokens](https://support.atlassian.com/bitbucket-cloud/docs/create-a-repository-access-token/).
```

2023-06-13 11:09 UTC, cafferata commented on doc/06-config.md
> +For example using `{"composer/composer": "example-access-token"}`.
Would it be good to use [the same](https://github.com/composer/composer/pull/11501/files#diff-2efd65948b461045cd73c395a83e71eeca38405bd2a65803933dc69bb5b6e3f1R382) example here?

""

```suggestion
For example using `{"workspace-name/repository-name": "repository-access-token"}`.
```

2023-06-13 15:17 UTC, BernhardK91 commented
@cafferata Thanks again for your suggestions. I agree with all and committed as suggested.

2023-06-21 14:21 UTC, Seldaek commented
Per @glaubinix's review this is not really workable without much more invasive changes so given there are already existing solutions via SSH keys + org wide oauth I would probably tend to say we rather not add this.

2023-07-11 07:40 UTC, closed without merging