Replace audit.ignore with audit.pass
composer/composer pull request #11605
Opened 2023-08-30 14:27 UTC by mxr576

Closes #11604

2023-08-30 14:28 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +            $io->writeError("<$errorOrWarn>Found $totalAdvisoryCount security vulnerability advisor{$plurality} affecting $affectedPackagesCount package{$pkgPlurality}{$punctuation}</$errorOrWarn>");
Do we want to change/extend this wording to better explain that "X number of vulnerabilities found, Y amount were silenced so X-Y caused the command failure"?

2023-08-30 15:31 UTC, Seldaek commented on src/Composer/Advisory/Auditor.php
> +            $io->writeError("<$errorOrWarn>Found $totalAdvisoryCount security vulnerability advisor{$plurality} affecting $affectedPackagesCount package{$pkgPlurality}{$punctuation}</$errorOrWarn>");
Yes definitely would need to clarify wording IMO.

2023-08-30 15:36 UTC, Seldaek commented on res/composer-schema.json
> +                        "pass": {
Not a fan of pass, but I will need to sleep over this one I think :)

2023-08-30 15:47 UTC, mxr576 commented on res/composer-schema.json
> +                        "pass": {
Me neither, maybe ignore remain as config key with different meaning.

2023-08-30 20:07 UTC, mxr576 commented on res/composer-schema.json
> +                        "pass": {
My current winner is `suppressed` and I am also thinking about turning the suppressed list to an associative array where the key would be the cve id and the value would be a mandatory human readonly description about why a vulnerability report was suppressed on the given project.

2023-08-31 08:24 UTC, Seldaek commented on res/composer-schema.json
> +                        "pass": {
I think I'd prefer `ignore` (not `ignored` as it was, that's my bad, `ignore` is more consistent with other directives in composer.json). But I agree having a reason in there makes sense for self documenting it. That's a good improvement.

2023-08-31 10:42 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +            $io->write(JsonFile::encode(['advisories' => $allAdvisories]));
How about introducing a new JSON output format that also contains the ignored vulnerabilities?

```json
{
  "advisories": {},
  "ignored-advisories": {}
}
```

For enabling the new format in the 2.x branch we could leverage a logic like ` if (Platform::getEnv('COMPOSER_AUDIT_FORMAT_VERSION') === '2.6.0') {}` or simiar.

2023-08-31 10:44 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +                $this->outputAdvisories($io, $ignoredAdvisories, $format);
Since we may have the reason for ignoring a given security advisory, I'd consider adding that to the output (also to the JSON above). What do you think?

2023-08-31 10:45 UTC, mxr576 commented on res/composer-schema.json
> +                        "pass": {
Switched back to `ignore` after checked the meaning of "suppress" vs "ignore".

2023-08-31 10:52 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +            $io->write(JsonFile::encode(['advisories' => $allAdvisories]));
Hm, maybe we do not even need a feature flag since we would only extend the object with a new property... :thinking:

2023-08-31 11:07 UTC, Seldaek commented on src/Composer/Advisory/Auditor.php
> +            $io->write(JsonFile::encode(['advisories' => $allAdvisories]));
Right, that sounds good to me, that's why I never do json objects with top level data directly. Always have top level keys so you can extend in a BC way :)

2023-08-31 11:09 UTC, Seldaek commented on src/Composer/Advisory/Auditor.php
> +            $io->write(JsonFile::encode(['advisories' => $allAdvisories]));
And I think I would not include the ignored ones in the `advisories` key in the json. I know they're all listed in one on the text output but for json it probably makes more sense to split them up.

2023-08-31 11:14 UTC, Seldaek commented on src/Composer/Advisory/Auditor.php
> +                $this->outputAdvisories($io, $ignoredAdvisories, $format);
Yes makes sense to me. It probably needs to be highlighted like `<warning>Ignored: $reason</>`

And for the table output add an Ignore column with `Yes`/empty and no reason to keep it small perhaps, because otherwise the table width will blow up

2023-08-31 11:27 UTC, Seldaek commented on src/Composer/Advisory/Auditor.php
> +          $advisories = $this->filterIgnoredAdvisories($advisories, $ignoredIds);
Indent seems off

```suggestion
            if (!\array_is_list($ignoredIds)) {
                $ignoredIds = array_keys($ignoredIds);
            }
            $advisories = $this->filterIgnoredAdvisories($advisories, $ignoredIds);
```

2023-08-31 11:32 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +                $this->outputAdvisories($io, $ignoredAdvisories, $format);
> Yes makes sense to me. It probably needs to be highlighted like <warning>Ignored: $reason</>

Just to be clear, do you mean display all ignore reasons as a console message unless the output format is JSON?

Speaking of JSON, partially because the JSON output leverages that advisories are JSON serializable, should I just introduce a new `class IgnoredSecurityAdvisory extends SecurityAdvisory{}` that can also hold the reason?

2023-08-31 11:32 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +            $io->write(JsonFile::encode(['advisories' => $allAdvisories]));
Added.

2023-08-31 11:40 UTC, Seldaek commented on src/Composer/Advisory/Auditor.php
> +                $this->outputAdvisories($io, $ignoredAdvisories, $format);
Yeah I was also wondering how to best achieve this. For sure for JSON it would be easier with a subclass.. 

For the plain text output I meant it probably should go here https://github.com/composer/composer/blob/main/src/Composer/Advisory/Auditor.php#L207 as a new line with a <warning> so it is highlighted as being ignored.

2023-08-31 11:49 UTC, Seldaek commented on src/Composer/Advisory/Auditor.php
> +          $ignoredAdvisories = $this->diffAdvisories($allAdvisories, $advisories);
Instead of adding a new method here I think I'd change filterIgnoredAdvisories to return `[$advisories, $ignoredAdvisories]` so you get it done in one go. Returning both there shouldn't be adding much complexity.

2023-08-31 13:06 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +          $ignoredAdvisories = $this->diffAdvisories($allAdvisories, $advisories);
Done: https://github.com/composer/composer/compare/99551b7f3f2478d1e5982af48f4b181a6c0edb8a..e570c5a1b9eaf67076c2336651fc6c4adac35576

This probably also helps with casting the ignored advisories to a new object as a next step

2023-08-31 13:51 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +                $this->outputAdvisories($io, $ignoredAdvisories, $format);
It seems to me that wrapping text in tables works OOTB, so is there any need for workarounds like...?

```
                $ignoreReason = '';
                if ($advisory instanceof IgnoredSecurityAdvisory && $advisory->ignoreReason !== NULL) {
                    if (strlen($advisory->ignoreReason) > 80) {
                        $ignoreReason = substr($advisory->ignoreReason, 0, 77) . '...';
                    }
                    else {
                        $ignoreReason = $advisory->ignoreReason;
                    }
                }
```

![image](https://github.com/composer/composer/assets/1755573/5cf0ae40-4550-4b9e-8fb9-947d2fd1b4d4)

2023-08-31 13:59 UTC, mxr576 commented on src/Composer/Advisory/IgnoredPartialSecurityAdvisory.php
> +        $data = parent::jsonSerialize();
I do not like traits with parent method calls so I rather copy-pasted these couple of lines.

2023-08-31 14:00 UTC, mxr576 commented on src/Composer/Advisory/SecurityAdvisory.php
> +     * @var non-empty-array<array{name: string, remoteId: string}>
PHPStan told me after that this was misaligned with the constructor.

2023-08-31 14:01 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +                $this->outputAdvisories($io, $ignoredAdvisories, $format);
https://github.com/composer/composer/compare/e570c5a1b9eaf67076c2336651fc6c4adac35576..708db5e9a4a47135753f938e87b3ba5646c4e1d0

2023-08-31 14:12 UTC, Seldaek commented on src/Composer/Advisory/IgnoredSecurityAdvisory.php
> +class IgnoredSecurityAdvisory extends SecurityAdvisory {
Could be marked final and `@internal` too I think.

2023-08-31 14:34 UTC, stof commented on src/Composer/Advisory/Auditor.php
> +                        $advisory = new IgnoredSecurityAdvisory(
should we create an object that extends SecurityAdvisory in which you copy all the metadata or should we rather have a `IgnoredSecurityAdvisory` that would take a `SecurityAdvisory|PartialSecurityAdvisory` as argument and implements its `jsonSerialize` method by adding an ignore_reason key in the array returned by the delegated call ?

2023-08-31 14:54 UTC, mxr576 commented on src/Composer/Advisory/IgnoredPartialSecurityAdvisory.php
> +        $data = parent::jsonSerialize();
Sounds reasonable, although the typehint on `\Composer\Advisory\Auditor::processAdvisories() ` (used to call `filterIgnoredAdvisories()`) said that PartialSecurityAdvisorys are potential value.

2023-08-31 14:55 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +     * @param array<string>|array<string,string> $ignoreList List of advisory IDs, remote IDs or CVE IDs that reported but not listed as vulnerabilities.
You are absolutely right, so rolling back to `string[]`.

2023-08-31 14:56 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +                        $advisory = new IgnoredSecurityAdvisory(
These were the options that I also considered, the solution in the PR just felt better, even if it is "ugly" a bit.

2023-08-31 15:05 UTC, mxr576 commented on src/Composer/Advisory/IgnoredPartialSecurityAdvisory.php
> +        $data = parent::jsonSerialize();
How about this?


https://github.com/composer/composer/compare/f7aff76e2d1dec71f0dfd392f5dc1b6398dbca8f..89eb824f52e19bf39ac87aef382783fcee0b8690

2023-08-31 15:08 UTC, mxr576 commented on src/Composer/Advisory/IgnoredPartialSecurityAdvisory.php
> +        $data = parent::jsonSerialize();
Got rid of the IgnoredPartialSecurityAdvisory

2023-08-31 15:14 UTC, fredden commented on src/Composer/Advisory/Auditor.php
> +                        $advisory = new IgnoredSecurityAdvisory(
Perhaps `IgnoredSecurityAdvisory` could be a proxy class or have a factory method which takes in a `SecurityAdvisory` object. That'd make the code here much cleaner.

`$advisory = IgnoredSecurityAdvisory::createFromSecurityAdvisory($advisory);` or `$advisory = new IgnoredSecurityAdvisory($advisory);`

2023-08-31 15:14 UTC, fredden commented on src/Composer/Advisory/Auditor.php
> +                        if ($ignoreReason !== NULL) {
I thought that the reason was a required field.

2023-08-31 15:20 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +                        $advisory = new IgnoredSecurityAdvisory(
`IgnoredSecurityAdvisory::createFromSecurityAdvisory($advisory`  I would have gone with this approach by default, but since everything in public on these objects (as public properties) this approach just moves copying object data to somewhere else. Would that have a real added value? In this case, should I make the constructor of `IgnoredSecurityAdvisory` private so it could be only constructed from a SecurityAdvisory from now?

2023-08-31 15:21 UTC, mxr576 commented on src/Composer/Advisory/Auditor.php
> +                        if ($ignoreReason !== NULL) {
Actually I decided to give more freedom to developers... so it cannot be mandatory.
https://github.com/composer/composer/pull/11605/files#diff-89992649ff6652d737d4dac645fbbac6ceeb112ab29010d0eaba3b42c658dc7eR112-R132

2023-08-31 20:01 UTC, naderman requested changes

2023-08-31 20:01 UTC, naderman commented on res/composer-schema.json
> +                                    "description": "A list of advisory ids, remote ids or CVE ids (keys) and the explanations (values) for why they're being ignored. The listed items are reported but
```suggestion
                                    "description": "A list of advisory ids, remote ids or CVE ids (keys) and the explanations (values) for why they're being ignored. The listed items are reported but let the audit command pass.",
```

2023-08-31 20:03 UTC, Seldaek commented
@mxr576 please don't change anything anymore, I'm editing a couple things here and then merging :) thanks a lot for the quick work here!

2023-08-31 20:27 UTC, Seldaek commented
I think it looks good now but I perhaps broke some tests.. anyway bedtime, will wrap up tomorrow.

2023-08-31 20:32 UTC, mxr576 commented
> @mxr576 please don't change anything anymore, I'm editing a couple things here and then merging :) thanks a lot for the quick work here!

Roger! 🙂 Time well spent! 🍻

2023-08-31 20:34 UTC, naderman approved these changes

2023-09-01 08:04 UTC, merged

2023-09-01 08:04 UTC, Seldaek commented
Ok looking good, thanks again.