Add release date to show command, and also release date for latest pa…
composer/composer pull request #11762
Opened 2023-12-19 13:38 UTC by Seldaek

…, fixes #11737

2023-12-19 13:39 UTC, Seldaek commented on src/Composer/Command/ShowCommand.php
> +        return $releaseDate->format('Y-m-d');
After a month I revert to just a date here. I don't know if X months ago would bring much more value or not? Any opinions?

2023-12-20 08:50 UTC, Seldaek commented on src/Composer/Command/ShowCommand.php
> +        return $releaseDate->format('Y-m-d');
Also note that I am showing the time since the release of the new package, not the old one. Were you expecting to see the old one? I am not sure what value either of these infos gives you in the outdated list view tbh.

2023-12-20 09:58 UTC, Seldaek commented on src/Composer/Command/ShowCommand.php
> +        return $releaseDate->format('Y-m-d');
Ok I added a --sort-by-age / -A flag now, so it shows the installed package's age only when the flag is used, and it also sorts then. That removes the confusion about what date is even shown as it is documented and opt-in.

2023-12-20 10:58 UTC, naderman requested changes

2023-12-20 10:58 UTC, naderman commented on doc/03-cli.md
> +* **--sort-by-age (-A):** Sort by and display current release age.
Same as above, should specify direction and "display installed version release age"

2023-12-20 10:58 UTC, naderman commented on src/Composer/Command/OutdatedCommand.php
> +                new InputOption('sort-by-age', 'A', InputOption::VALUE_NONE, 'Sort by and display current release age.'),
Same as above, should specify direction and "display installed version release age"

2023-12-20 10:58 UTC, naderman commented on src/Composer/Command/ShowCommand.php
> +                new InputOption('sort-by-age', 'A', InputOption::VALUE_NONE, 'Sort by and display current release age. Use with the --latest or --outdated option.'),
Same as above, should specify direction and "display installed version release age"

2023-12-20 10:58 UTC, naderman commented on src/Composer/Command/ShowCommand.php
> +                        return 0;
Huh, what else can go in here than objects?

2023-12-20 10:58 UTC, naderman commented on src/Composer/Command/ShowCommand.php
> +            return floor($diff->days / 7) . ' weeks ago';
Why floor instead of round?

2023-12-20 13:04 UTC, Seldaek commented on src/Composer/Command/ShowCommand.php
> +            return floor($diff->days / 7) . ' weeks ago';
Because 2 weeks and 6 days isn't 3 weeks?

2023-12-20 13:31 UTC, naderman commented on src/Composer/Command/ShowCommand.php
> +            return floor($diff->days / 7) . ' weeks ago';
Closer to 3 weeks than it is to 2 weeks, nature of rounding? :-P

2023-12-20 14:17 UTC, Seldaek commented on src/Composer/Command/ShowCommand.php
> +                        return 0;
When you list everything we only get strings for package names from packagist.org - so it's not always objects, but in relevant cases where --latest would be yes they should always be.

2023-12-20 14:18 UTC, naderman commented on src/Composer/Command/ShowCommand.php
> +                        return 0;
Ah okay, I see.

2023-12-20 14:37 UTC, merged

2024-10-30 17:47 UTC, HeenaBansal20 commented
@Seldaek ,  I was trying the show command like below , but the output didn't show the released date of the requested package. Do I need to add some other arg to get the release date

`composer show --available --format=json --ignore-platform-reqs --latest --sort-by-age  yiisoft/yii2 `

2024-10-30 19:15 UTC, Seldaek commented
This doesn't work with --available I'm afraid, only for installed packages.

2024-10-30 20:16 UTC, HeenaBansal20 commented
> This doesn't work with --available I'm afraid, only for installed packages.

hmm.. What exactly this argument `--available ` is for , removing --available from command also didn't show up the release dates.


> --available (-a): List available packages only.

2024-10-30 20:17 UTC, HeenaBansal20 commented
> > This doesn't work with --available I'm afraid, only for installed packages.
> 
> hmm.. What exactly this argument `--available ` is for , removing --available from command also didn't show up the release dates.
> 
> > --available (-a): List available packages only.

Basically , I want to get the release date for latest version of this package. Is there any way from show command I can get the release date of the packages.

2024-10-30 20:22 UTC, Seldaek commented
For an installed package I do see it:

```
$ composer show --format=json --ignore-platform-reqs --latest --sort-by-age  composer/semver | grep release
    "released": "2024-09-19T14:15:21+00:00",
```

In my case composer/semver is installed. --available makes it check all packages on packagist and not just installed, so it runs slower and lists multiple versions so there is no release date I think