Refactor proxy handling to require https_proxy
composer/composer pull request #11915
Opened 2024-04-03 19:59 UTC by johnstevenson

Composer has always allowed a single http_proxy (or CGI_HTTP_PROXY) environment variable to be used for both HTTP and HTTPS requests. But many other tools and libraries require scheme-specific values.

The landscape is already complicated by the use of and need for upper and lower case values, so to bring matters inline with current practice https_proxy is now required for HTTPS requests.

The new proxy handler incorporates a transition mechanism, which allows http_proxy to be used for all requests when https_proxy is not set and provides a `needsTransitionWarning` method for the main application.

Moving to scheme-specific environment variables means that a user may set a single proxy for either HTTP or HTTPS requests. To accomodate this situation during the transition period, an https_proxy value can be set to an empty string which will prevent http_proxy being used for HTTPS requests.

**Summary**
- Everything works as before
- If a user has a single http_proxy and it is used for HTTPS requests, a warning message is shown after any other output:

```txt
Composer now requires separate proxy environment variables for HTTP and HTTPS requests.
Please set `https_proxy` in addition to your existing proxy environment variables.
```
**Implementation**
The refactoring was such that it was easier to replace the old `ProxyManager` class with a new `ProxyHandler`. In part this was because the original implementation was very rushed to meet the Composer 2 deadline and some unused artifacts from a last minute refactoring of that remained.

There are two small differences:

1. Previously a CGI_HTTP_PROXY value overwrote any http_proxy value when in a CLI environment. Now CGI_HTTP_PROXY (and also cgi_http_proxy which is something Ruby now uses) is only examined if no http_proxy was found. I cannot see this making a difference.

2. The previous `getProxyForRequest` method obtained the url scheme from `parse_url($requestUrl, PHP_URL_SCHEME) ?: 'http'`, which had the unfortunate effect of turning a `false` value into http (like when Windows file urls are used in a couple of tests). The latest version uses `(string) parse_url($requestUrl, PHP_URL_SCHEME)`. My concern is that valid request urls without a scheme are now not converted to http and will bypass any proxy. It is likely there are such urls?

The warning message is only shown if a command makes an HTTPS request, but it could easily be changed to show after every command.

This is a follow up to discussions on #11876

2024-04-06 17:58 UTC, johnstevenson commented
Apologies, for the forced-push, but I've updated this to remove some bits that I thought might be needed for the Diagnose command, which it turns out were not. I will provide a separate PR for that later, to bring it up to date with these changes.

I've also fixed some code that was changed in `CurlDownloader::initDownload()` as part of some PHPStan improvements in 8600894003. This changed setting CURLOPT_PROXY with an empty proxy url. However, this is needed because it prevents curl from reading any proxy environment variables (which we have already handled).

The CI tests are now failing on PHP 8.3 and below because StatusCommandTest::testLocallyModifiedPackages() fetches https://www.smarty.net/files/Smarty-3.1.7.zip and that domain name expired on 2024-04-05 is now parked.

2024-04-12 21:59 UTC, Seldaek commented
Oh boy.. I thought it was going to be a reasonably small fix 😅  Thanks, but it will take me some time to review.

2024-04-13 11:13 UTC, johnstevenson commented
> I thought it was going to be a reasonably small fix

I did try multiple ways to keep the noise down in the diff, but to no avail.

Perhaps we could do it in the same way we reworked the installer script years ago, by breaking it down into a series of PRs that add functionality by stages?

As a first step, I could provide a new PR that simply adds the new ProxyHandler and ProxyItem classes without plumbing them in, which would make reviewing the functionality much easier.

I don't mind doing this, because I already have a some improvements on this PR yet to push, and in retrospect I think it would make your life easier.

>  it will take me some time to review.

There's no great rush here to add this change, but please let me know if you would prefer the above approach.

2024-04-13 11:31 UTC, Seldaek commented
No i think it's fine, i can review those new files in isolation from the other changes anyway. Feel free to add whatever is needed here. I won't look until monday earliest

2024-04-14 17:02 UTC, johnstevenson commented
5325ed9 changes how userinfo is set for curl by stripping it out of the proxy url and adding it with the `CURLOPT_PROXYUSERPWD` option. This is done because  some curl versions will show userinfo in the error message when given a malformed url.

It also takes the choice of the curl proxy options out of CurlDownloader and lets RequestProxy provide them as an array.

2024-04-15 15:22 UTC, Seldaek commented on src/Composer/Util/Http/ProxyHandler.php
> +class ProxyHandler
I understand this is a full rewrite here but can we maybe keep the ProxyManager name? Or what's the reasoning for changing it (besides the fact I'm sure it was easier for you while rewriting side by side?).

2024-04-15 15:26 UTC, Seldaek commented on src/Composer/Util/Http/ProxyHandler.php
> +    /** @var ?ProxyHandler */
```suggestion
    /** @var ?self */
```

2024-04-15 15:41 UTC, Seldaek commented on src/Composer/Console/Application.php
> +                $io->writeError('<warning>Please set `https_proxy` in addition to your existing proxy environment variables.</warning>');
```suggestion
                $io->writeError('<warning>Please set `https_proxy` in addition to your existing proxy environment variables.</warning>');
                $io->writeError('<warning>This fallback (and warning) will be removed in Composer 2.8.0.</warning>');
```

2024-04-15 15:49 UTC, Seldaek commented on src/Composer/Util/Http/ProxyHandler.php
> +            if (is_string($_SERVER[$name] ?? null)) {
Please use Platform::getEnv here, which will return false if the var is unset

2024-04-15 16:04 UTC, Seldaek commented on src/Composer/Util/Http/ProxyHandler.php
> +        return new RequestProxy($url, $auth, $options, $info);
IMO this would read better with a few factory methods hiding all the copying around of stuff:

```suggestion
        $proxy = $this->getProxyForScheme($scheme);

        if ($proxy === null) {
            return RequestProxy::none();
        }

        if ($this->noProxy($requestUrl)) {
            return RequestProxy::noProxy();
        }

        return RequestProxy::fromProxyItem($scheme);
```

2024-04-15 16:13 UTC, Seldaek commented on src/Composer/Util/Http/ProxyItem.php
> +        }
Maybe move this check to ProxyHandler::getProxyEnv, then it can simply return $env and no name, and this class doesn't need $envName either.

2024-04-15 16:15 UTC, Seldaek commented on src/Composer/Util/Http/ProxyItem.php
> +        }
Ah no sorry you kinda need that as checkData can return false too. But I'd still rather move this whole check in checkData, or just move checkData body to be the constructor body, so you can throw proper exception message withw hat is unsupported instead of just a generic throw when checkData returns false.

2024-04-15 19:22 UTC, Seldaek requested changes
Ok done reviewing, beyond the few small code changes which IMO would improve readability (I struggled in a few places, but eventually grasped things, it's just code style mostly I think..) I think it looks good to me, thanks!

2024-04-16 12:37 UTC, johnstevenson commented on src/Composer/Util/Http/ProxyHandler.php
> +class ProxyHandler
Yes we can keep the name. The reasoning was exactly as you suggest from a rewriting perspective, but also to avoid a messy ProxyManager diff from a reviewing perspective. Of course, this hasn't really worked given the overall changes!

2024-04-16 12:47 UTC, johnstevenson commented on src/Composer/Util/Http/ProxyHandler.php
> +    /** @var ?ProxyHandler */
Yes, will fix.

2024-04-16 13:00 UTC, johnstevenson commented on src/Composer/Console/Application.php
> +                $io->writeError('<warning>Please set `https_proxy` in addition to your existing proxy environment variables.</warning>');
> it just behaves as it did before if only http_proxy is set, correct?

Yes, that is correct. I'll add the additional warning.

Incidentally, I intend to submit a PR for a new `how-to-use-composer-behind-a-proxy` FAQ, which will detail the requirements and replace the info from the environment variables section (with a suitable reference). This could perhaps be added to the warning message later, if it is accepted.

2024-04-16 13:51 UTC, johnstevenson commented on src/Composer/Util/Http/ProxyHandler.php
> +            if (is_string($_SERVER[$name] ?? null)) {
We have always used $_SERVER because it provides case-sensitive matching, which is crucial, while `getenv` (used by Platform::getEnv, although only as a fallback) does not. Additionally getenv would need to use the `local` param in order not to evaluate SAPI specific environment variables, though this wouldn't fix the case-insensitivity.

I'd prefer to keep this as it is, in house (as it were).

2024-04-16 13:53 UTC, johnstevenson commented on src/Composer/Util/Http/ProxyHandler.php
> +        return new RequestProxy($url, $auth, $options, $info);
Neat. I really like this and will implement.

2024-04-16 19:10 UTC, Seldaek commented on src/Composer/Util/Http/ProxyHandler.php
> +            if (is_string($_SERVER[$name] ?? null)) {
Alright then leave it as is.

2024-04-17 12:10 UTC, Seldaek commented on src/Composer/Console/Application.php
> +                $io->writeError('<warning>Please set `https_proxy` in addition to your existing proxy environment variables.</warning>');
Sounds good to have better docs on this 👍🏻

2024-04-17 12:11 UTC, Seldaek approved these changes
Looks good to me now, thanks! Anything else coming or good to merge for you as well?

2024-04-17 12:24 UTC, johnstevenson commented
Yes, it's good to merge for me. I've got a Diagnose update and a docs update but I was going to PR them separately.

2024-04-17 12:34 UTC, Seldaek commented
Nah it's fine as is I think for the warning. And yes separate PRs later for the rest sounds good, also would appreciate a PR to clean up the transitional stuff for 2.8 but it's not urgent.

I'll merge this then, thanks again

2024-04-17 12:34 UTC, merged