Add option to run bump after update
composer/composer pull request #11942
Opened 2024-04-22 11:48 UTC by carlos-granados

- Adds a new `bump-after-update` config parameter
- Adds a new `bump-after-update` option to the update command
- Adds two new `bump-dev-only` and `bump-no-dev-only` options to the update command

If the `bump-after-update` config parameter is set or the `bump-after-update` option is passed to the `update` command, it will run the `bump` command after finishing the update. This command will only be run if the update finishes successfully

If the `bump-dev-only` or `bump-no-dev-only` options are passed to the `update`  command, only the dev or non-dev requires will be updated

The `dry-run` option passed to the `update` command will also be used for the `bump` command

If any packages are listed in the `update` command, this same package list will be used by the `bump` command.

Includes updates to the documentation and new tests

Fixes https://github.com/composer/composer/issues/11906

2024-04-22 14:05 UTC, carlos-granados commented on tests/Composer/Test/Command/UpdateCommandTest.php
> +        if ($createLock) {
The bump command needs that a lock file exist, so when testing the `bump-after-update` version we need to create one

2024-04-23 11:43 UTC, Seldaek requested changes
Thanks for the PR, after a quick review just one comment but I'll need to take a closer look when I'm back at my desk :)

2024-04-23 11:43 UTC, Seldaek commented on doc/06-config.md
> +Defaults to false. If set to true, Composer will run the Bump command after running
I think this could be a string|bool that also accepts "no-dev" and "dev" as values to configure the `*-only` flags.

2024-04-23 11:46 UTC, carlos-granados commented on doc/06-config.md
> +Defaults to false. If set to true, Composer will run the Bump command after running
This suggestion sounds good. I'll wait until you come back and are able to take a deeper look. If you still feel this is the way to go, I'll modify the PR

2024-04-28 15:29 UTC, Seldaek commented on doc/06-config.md
> +Defaults to false. If set to true, Composer will run the Bump command after running
Yes please :) Definitely feel like this would be an improvement.

2024-04-28 15:30 UTC, Seldaek commented on src/Composer/Command/BumpCommand.php
> +        bool $calledFromUpdate = false
Seems unused and unnecessary?

2024-04-28 15:31 UTC, Seldaek commented on src/Composer/Command/UpdateCommand.php
> +                $io->writeError('<info>Running Bump after Update.</info>');
```suggestion
                $io->writeError('<info>Bumping dependencies</info>');
```

2024-04-28 15:32 UTC, Seldaek commented on src/Composer/Command/UpdateCommand.php
> +                $io->writeError('<warning>Not running Bump after Update because the update command did not finish successfully.</warning>');
I don't think this is needed.

```suggestion
```

2024-08-30 11:31 UTC, cafferata commented
Hi @Seldaek, is there a reason why this GitHub pull request was not receive a (re)review the past four months? Has this perhaps been lost sight of? No rush, I saw other GitHub pull requests being reviewed/merged. So I was wondering how this works within your available time. Of course an answer of no time/priority is also completely valid. ☺️

2024-09-02 08:54 UTC, Seldaek commented
It's just targetting 2.8 and I was focused on shipping patch releases for 2.7 so far.. kinda buffering 2.8 PRs until I'm ready to work on those because once I branch it out then I need to merge 2.7 into 2.8 which is more work for me.

2024-09-02 15:45 UTC, lyrixx commented
Oh, thanks for this PR. I had spare time, and decided to try to fix my issue. And I totally miss your PR :/ 
For the record, I had another approach, were I factorized the code in a new service: https://github.com/lyrixx/composer/commit/df8a25bf8f2b215545a79f1f07352bd35fe91246

2024-09-18 13:20 UTC, Seldaek approved these changes
Mostly found some minor wording style issues, and one minor edge case in the code, overall pretty solid PR thanks! And sorry for the delay :)

2024-09-18 13:20 UTC, Seldaek commented on doc/03-cli.md
> +* **--bump-after-update:** Runs Bump after performing the update. Set to `dev` or `no-dev` to only bump those dependencies.
```suggestion
* **--bump-after-update:** Runs `bump` after performing the update. Set to `dev` or `no-dev` to only bump those dependencies.
```

2024-09-18 13:20 UTC, Seldaek commented on doc/06-config.md
> +the Update command. If set to `"dev"` or `"no-dev"` then only the corresponding dependencies will be bumped.
```suggestion
Defaults to `false` and can be any of `true`, `false`, `"dev"` or `"no-dev"`. If set to true, Composer will run the `bump` command after running
the `update` command. If set to `"dev"` or `"no-dev"` then only the corresponding dependencies will be bumped.
```

2024-09-18 13:20 UTC, Seldaek commented on res/composer-schema.json
> +                    "description": "Defaults to false and can be any of true, false, \"dev\"` or \"no-dev\"`. If set to true, Composer will run the Bump command after running the Update command. If s
```suggestion
                    "description": "Defaults to false and can be any of true, false, \"dev\"` or \"no-dev\"`. If set to true, Composer will run the bump command after running the update command. If set to \"dev\" or \"no-dev\" then only the corresponding dependencies will be bumped."
```

2024-09-18 13:20 UTC, Seldaek commented on src/Composer/Command/BumpCommand.php
> +                $io->writeError('<warning>Alternatively you can use the dev-only option to only bump dependencies within "require-dev".</warning>');
```suggestion
                $io->writeError('<warning>Alternatively you can use --dev-only to only bump dependencies within "require-dev".</warning>');
```

2024-09-18 13:20 UTC, Seldaek commented on src/Composer/Command/UpdateCommand.php
> +                new InputOption('bump-after-update', null, InputOption::VALUE_NONE, 'Runs Bump after performing the update.'),
```suggestion
                new InputOption('bump-after-update', null, InputOption::VALUE_OPTIONAL, 'Runs bump after performing the update.', false, ['dev', 'no-dev', 'all']),
```

2024-09-18 13:20 UTC, Seldaek commented on src/Composer/Command/UpdateCommand.php
> +            }
Doing `$input->getOption('bump-after-update') === 'dev' || $composer->getConfig()->get('bump-after-update') === 'dev',` here isn't very safe as you might end up with only dev AND only non-dev if you have the config set to no-dev and the option set to --bump-after-update=dev then both will be true.

```suggestion
            $bumpAfterUpdate = $input->getOption('bump-after-update');
            if (false === $bumpAfterUpdate) {
                $bumpAfterUpdate = $composer->getConfig()->get('bump-after-update');
            }

            if (false !== $bumpAfterUpdate) {
                $io->writeError('<info>Bumping dependencies</info>');
                $bumpCommand = new BumpCommand();
                $bumpCommand->setComposer($composer);
                $result = $bumpCommand->doBump(
                    $io,
                    $bumpAfterUpdate === 'dev',
                    $bumpAfterUpdate === 'no-dev',
                    $input->getOption('dry-run'),
                    $input->getArgument('packages')
                );
            }
```

2024-09-18 13:27 UTC, Seldaek commented on tests/Composer/Test/Command/UpdateCommandTest.php
> +<warning>Alternatively you can use the dev-only option to only bump dependencies within "require-dev".</warning>
```suggestion
<warning>Alternatively you can use --dev-only to only bump dependencies within "require-dev".</warning>
```

2024-09-18 13:34 UTC, merged

2024-11-04 14:07 UTC, stof commented on res/composer-schema.json
> +                    "type": ["string", "boolean"],
this should use `enum` to restrict the supported strings

2024-11-04 14:10 UTC, stof commented on tests/Composer/Test/Command/UpdateCommandTest.php
> +<warning>Alternatively you can use --dev-only to only bump dependencies within "require-dev".</warning>
this `--dev-only` option is confusing when running this as part of `composer update` instead of `composer bump`

2024-11-04 14:10 UTC, stof commented on src/Composer/Command/UpdateCommand.php
> +                new InputOption('bump-after-update', null, InputOption::VALUE_OPTIONAL, 'Runs bump after performing the update.', false, ['dev', 'no-dev', 'all']),
using `InputOption::VALUE_OPTIONAL` is confusing here, because it makes `composer update --bump-after-update` valid during argument validation, but this would still make it use the default value (i.e. `false`). This should probably be using `VALUE_REQUIRED` instead.

2025-11-12 10:45 UTC, Seldaek commented on src/Composer/Command/UpdateCommand.php
> +                new InputOption('bump-after-update', null, InputOption::VALUE_OPTIONAL, 'Runs bump after performing the update.', false, ['dev', 'no-dev', 'all']),
This is actually not an issue as with VALUE_OPTIONAL when you just do --flag the value is `null`, and not the default value (`false` here).