Composer 2: Adapt file download cache keys to changed processed URLs
composer/composer pull request #9220
Opened 2020-09-16 09:25 UTC by ffraenz

Following up the introduction of a `setProcessedUrl` method on the `PreFileDownloadEvent` in https://github.com/composer/composer/pull/8975 we found another issue that is blocking us from upgrading plugins to Composer 2. When altering the `processedUrl` for packages the file download `cacheKey` unexpectedly does not change with it, potentially reusing outdated files.

I am therefore suggesting that the cache key gets regenerated when the processed URL gets changed during `PreFileDownloadEvent` dispatching.

For [use cases](https://github.com/ffraenz/private-composer-installer/pull/25#issuecomment-692792485) that introduce temporary processed URLs (e.g. timestamps, session tokens, etc.) further optimization may be possible by allowing plugin authors to optionally provide a custom cache key in `PreFileDownloadEvent`. They may leave time-related params out of the value from which the cache key hash is generated.

The two proposed changes only apply to file downloads of type `package` as the cache keys of `metadata` downloads do not depend on the processed URL.

/cc @mcaskill

2020-09-16 17:37 UTC, stof requested changes

2020-09-16 17:37 UTC, stof commented on src/Composer/Plugin/PreFileDownloadEvent.php
> +     * @return string
`string|null` is the right type.

2020-09-16 17:37 UTC, stof commented on src/Composer/Plugin/PreFileDownloadEvent.php
> +     * @param string $customCacheKey New cache key
`string|null` is the right type.

2020-09-16 17:37 UTC, stof commented on src/Composer/Plugin/PreFileDownloadEvent.php
> +     * @var string
`string|null` is the right type.

2020-09-16 18:14 UTC, ffraenz commented on src/Composer/Plugin/PreFileDownloadEvent.php
> +     * @return string
Thank you for the heads up. I fixed the PHPDoc types on this property.

2020-10-01 19:27 UTC, GrahamCampbell requested changes

2020-10-01 19:27 UTC, GrahamCampbell commented on src/Composer/Downloader/FileDownloader.php
> +        $generateCacheKey = function (PackageInterface $package, $key) {
`$cacheKeyFactory` or `$cacheKeyGenerator` is probably a better name of that variable.

2020-10-01 19:27 UTC, GrahamCampbell commented on src/Composer/Downloader/FileDownloader.php
> +            $cacheKey = sha1($key);
Need a blank line before the return statement.

2020-10-05 18:41 UTC, mcaskill commented
@ffraenz If there's a way to add me as a collaborator on this pull request, it would my pleasure to help with any changes requested by the Composer team.

2020-10-05 18:54 UTC, ffraenz commented on src/Composer/Downloader/FileDownloader.php
> +        $generateCacheKey = function (PackageInterface $package, $key) {
Thank you for bringing this up. I renamed the variable to `$cacheKeyGenerator`.

2020-10-05 18:54 UTC, ffraenz commented on src/Composer/Downloader/FileDownloader.php
> +            $cacheKey = sha1($key);
Done!

2020-10-05 18:59 UTC, ffraenz commented
@mcaskill I added you to the PR repository, you should be able to push into it.

2020-10-12 14:55 UTC, Seldaek commented
Thanks, looks good!

2020-10-12 14:55 UTC, merged

2020-10-15 18:26 UTC, mcaskill commented
Hi @ffraenz,

I've been testing out 2.0.0-RC2 and I've noticed we missed how `FileDownloader::download()` defines and uses its callback functions (`$download`, `$accept`, `$reject`). The `$urls` variable is passed by reference to each callback but the manipulations, in `$download`, made to `$url` are done on a copy:

```php
$download = function () use ($io, $output, $httpDownloader, $cache, $cacheKeyGenerator, $eventDispatcher, $package, $fileName, &$urls, &$accept, &$reject) {
    $url = reset($urls);
```

Once `$accept` is called, it still has the original dataset:

```php
$accept = function ($response) use ($cache, $package, $fileName, $self, &$urls) {
    $url = reset($urls);
```

We would need to do the following to ensure the manipulated `$url` is reflected on `$urls`:

```php
$download = function () use ($io, $output, $httpDownloader, $cache, $cacheKeyGenerator, $eventDispatcher, $package, $fileName, &$urls, &$accept, &$reject) {
    $url   = reset($urls);
    $index = key($urls);

    if ($eventDispatcher) {
        // ...
    }

    $urls[$index] = $url;
```

Also, I'm still having issues with extracting the cached package and writing the filtered dist URL to the lock file. I've finally installed the Composer repository to be able to tinker with it while testing out our plugins.

Have you noticed these issues or anything else?

Thanks,

P.S.: @Seldaek Sorry, for the incomplete testing and implementation of this pull request.

2020-10-15 19:49 UTC, Seldaek commented
@mcaskill no worries, just glad if you can send a PR but no rush, I don't really think this stuff affects anyone else right now.

2020-10-15 20:25 UTC, mcaskill commented
Regarding the filtering of the dist URL for the lock file, I've got that resolved.

Plugin developers that need to manipulate the dist URL will need to use `PRE_POOL_CREATE` in Composer v2 and `PRE_PACKAGE_INSTALL` and `PRE_PACKAGE_UPDATE` in Composer v1.

Note: in using `PRE_POOL_CREATE`, we technically don't need `PreFileDownloadEvent::setCustomCacheKey()` after all (confirmed but unsubstantiated) but its presence does require developers to explicitly assign a custom cache key to prevent the manipulated processed URL from overwriting the original cache key.

On my end, all that's left to resolve is the extraction of the cached package. I still end up with an empty directory where the package should be.