Refactor proxy handling for Composer2
composer/composer pull request #9324
Opened 2020-10-22 20:12 UTC by johnstevenson

First attempt at fixing the issues highlighted in https://github.com/composer/composer/issues/9314

* ProxyHelper is a utility class that process the environment variables. I've split this out from StreamContextFactory so it can be more easily used by the installer.
* ProxyManager uses the ProxyHelper to provide the context options for streams, and the proxy url for curl. It's a singleton class but I couldn't find any other way of doing it.

In the rare cases of a secure proxy, PHP streams will fail in the case of an https request (in a similar way that a missing openssl extension does). The curl handling also takes a request based approach - however curl cannot handle http requests either so it could lead to a situation where using streams would have worked.

2020-10-23 07:59 UTC, Seldaek requested changes

2020-10-23 07:59 UTC, Seldaek commented on src/Composer/Util/Http/CurlDownloader.php
> +        $proxyUrl = $this->proxyManager->getCurloptProxy($url, $secureProxy);
Could this use `list($proxyUrl, $isSecureProxy) = ...` kind of pattern instead of references? References are really not helping readability, it might make sense when you wrote the code but here I just have to guess at what is going on..

2020-10-23 07:59 UTC, Seldaek commented on src/Composer/Util/Http/CurlDownloader.php
> +        $ifModified = false !== strpos(strtolower(implode(',', $options['http']['header'])), 'if-modified-since:') ? ' if modified' : '';
Why the change from stripos? This doesn't seems like an improvement?

2020-10-23 07:59 UTC, Seldaek commented on src/Composer/Util/ProxyManager.php
> +            $this->info = implode(', ', $info);
Generally here too this is super hard to read.. I have no idea what's in $info, I look up and see it's again some by ref argument.. Why isn't setData returning the $info data? Why is it called $info if it represents the safe proxy url? `$safeProxyUrl = $this->setData(...)` would be clearer I'd think.

2020-10-23 07:59 UTC, Seldaek commented on src/Composer/Util/Http/CurlDownloader.php
> +        $usingProxy = $this->proxyManager->getLastProxy(' using proxy (%s)');
I was fine with a singleton but now it looks like it's a stateful one too, which makes things really hard to follow and bug prone IMO.

How about converting ProxyManager to something like a ProxyConfig class, which an instance of is created for every request here, it can have a static var for the constant config/state stuff so it doesn't need to recompute it all on every request, but IMO it'd make things much easier, would allow it to have simple getters for values which are sure to be linked to the current URL being processed, no state changes, no by-reference args.

2020-10-23 07:59 UTC, Seldaek commented on src/Composer/Util/ProxyHelper.php
> +        return self::formatParsedUrl($parts, $includeAuth = true);
I think this whole method could be replaced by `Composer\Util\Url::sanitize($proxyUrl)`

2020-10-23 08:01 UTC, Seldaek commented
Also please move those new Proxy* classes into Composer\Util\Http namespace I think it'd make more sense as they are internal.

2020-10-23 09:54 UTC, johnstevenson commented on src/Composer/Util/ProxyManager.php
> +            $this->info = implode(', ', $info);
Yeah, it's rubbish . I had to remind myself what it is (which is a scheme=safeUrl pair). I'm not sure it's even needed now.

2020-10-23 09:55 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +        $ifModified = false !== strpos(strtolower(implode(',', $options['http']['header'])), 'if-modified-since:') ? ' if modified' : '';
Hmm, I must have screwed up a rebase merge confilct (I hadn't realised this line had change)

2020-10-23 09:56 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +        $proxyUrl = $this->proxyManager->getCurloptProxy($url, $secureProxy);
Yes, I agree.

2020-10-23 10:10 UTC, stof commented on src/Composer/Util/Http/CurlDownloader.php
> +                $message = 'Connecting to a secure proxy using curl is not supported on PHP versions below 7.3.0.';
why using a variable for the message instead of inlining it ?

2020-10-23 10:10 UTC, stof commented on src/Composer/Util/Http/CurlDownloader.php
> +        $options = StreamContextFactory::initOptions($url, $options, $forCurl = true);
why defining a `$forCurl` local variable here ? That's useless as you don't use it.

2020-10-23 10:28 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +        $usingProxy = $this->proxyManager->getLastProxy(' using proxy (%s)');
Yes that makes more sense: perhaps the ProxyManager could become a ProxyFactory, which stores the state and creates a ProxyConfig (or something) class per request. I originally designed it to be session based, with the HttpDownloader determining if curl is compatible - and using streams if it isn't.

A properly implemented request based approach will make things cleaner - with the proviso that folks using a secure-proxy need PHP 7.3+ and curl (and won't be able to make http requests any more).

2020-10-23 10:28 UTC, johnstevenson commented on src/Composer/Util/ProxyHelper.php
> +        return self::formatParsedUrl($parts, $includeAuth = true);
Will do.

2020-10-23 10:38 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +                $message = 'Connecting to a secure proxy using curl is not supported on PHP versions below 7.3.0.';
Agree, there is no need for that (the message was a bit more complicated at one point involving curl versions, until I discovered that even PHP 5.6 supports the version but not the feature)

2020-10-23 10:41 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +        $options = StreamContextFactory::initOptions($url, $options, $forCurl = true);
To make a boolean flag more descriptive and the comment easier to write/understand, but I can remove it if you want?

2020-10-23 10:55 UTC, stof commented on src/Composer/Util/Http/CurlDownloader.php
> +        $options = StreamContextFactory::initOptions($url, $options, $forCurl = true);
But then, phpstan (and IDEs) would complain about an unused variable (phpstan does not complain right now because composer runs it at a very low level and this rule is at a higher level).
Regarding the behavior of `$forCurl == true`, the proper place to document its effect would be in the phpdoc of `StreamContextFactory::initOptions` IMO, not on the usage

2020-10-23 10:57 UTC, johnstevenson commented on src/Composer/Util/ProxyHelper.php
> +        return self::formatParsedUrl($parts, $includeAuth = true);
Oops, that last reply was intended to be to "Also please move those new Proxy* classes into Composer\Util\Http namespace I think it'd make more sense as they are internal."

I had hoped that it would do the job, but it doesn't work without a scheme. Incidentally, the ProxyHelper version masks the user but Url::sanitize does not - so is it safe (good practice) to show the user part ?

2020-10-23 11:05 UTC, Seldaek commented on src/Composer/Util/ProxyHelper.php
> +        return self::formatParsedUrl($parts, $includeAuth = true);
Well generally speaking showing the user can help people spot misconfiguration I'd think. Feel free to tweak the sanitize method so it handles URLs without scheme tho. I guess turning `://` into `(://|^)` in the regex and then returning $m[1] instead of :// should do.

2020-10-23 11:26 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +        $options = StreamContextFactory::initOptions($url, $options, $forCurl = true);
Thanks for explaining, I hadn't realised the phpstan bit.

2020-10-23 13:55 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +        $options = StreamContextFactory::initOptions($url, $options, $forCurl = true);
Resolved in Code review:1 fixes

2020-10-23 13:55 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +        $ifModified = false !== strpos(strtolower(implode(',', $options['http']['header'])), 'if-modified-since:') ? ' if modified' : '';
Resolved in Code review:1 fixes

2020-10-23 13:55 UTC, johnstevenson commented on src/Composer/Util/ProxyHelper.php
> +        return self::formatParsedUrl($parts, $includeAuth = true);
Resolved in Code review:1 fixes

2020-10-23 13:56 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +                $message = 'Connecting to a secure proxy using curl is not supported on PHP versions below 7.3.0.';
Resolved in Code review:1 fixes

2020-10-23 18:17 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +        $proxyUrl = $this->proxyManager->getCurloptProxy($url, $secureProxy);
Resolved in Refactor ProxyManager

2020-10-23 18:17 UTC, johnstevenson commented on src/Composer/Util/Http/CurlDownloader.php
> +        $usingProxy = $this->proxyManager->getLastProxy(' using proxy (%s)');
Resolved in Refactor ProxyManager

2020-10-23 18:18 UTC, johnstevenson commented on src/Composer/Util/ProxyManager.php
> +            $this->info = implode(', ', $info);
Resolved in Refactor ProxyManager

2020-10-23 19:09 UTC, johnstevenson commented
@Seldaek Okay, we're almost there. I need to add tests to the `RequestProxy` class (terrible name) but the core data is already covered so these can wait.

I'm going to spend a short time running it through my secure-proxy implementation, then I'll rebase it all. Shout now if you want anything changing or spot something that is glaringly awful or just plain wrong.

2020-10-23 20:41 UTC, johnstevenson commented
Squashed and rebased. It appears to work well running it through a proxy.

2020-10-24 08:37 UTC, Seldaek approved these changes
Looks fine overall so merging, still left a couple comments and fixed a couple things myself in 62eff8e979a5adeffc2b5490f581d5ea5bbf008e

2020-10-24 08:37 UTC, Seldaek commented on src/Composer/Util/Http/CurlDownloader.php
> +        // Merge in headers - we don't get any proxy values
Not sure I understand what this means.. We don't get any proxy values? And what merging of headers?

2020-10-24 08:37 UTC, Seldaek commented on src/Composer/Util/StreamContextFactory.php
> +                    throw new TransportException('PHP does not support https requests to a secure proxy.');
Maybe suggest enabling the curl extension, and specify that PHP **streams** do not support this? Generally speaking the more verbose and helpful the errors are the better, if they allow people to fully understand or at least fix the problem without reaching out to us.

2020-10-24 08:37 UTC, merged