Add article on resolving merge conflicts
composer/composer pull request #9386
Opened 2020-10-30 16:07 UTC by PrinsFrank

2020-11-01 15:38 UTC, PrinsFrank commented
@lpeabody I'm not familiar with it, so I don't really know what to write here. What change in the article would you suggest?

2020-11-01 17:27 UTC, lpeabody commented
It's a tool that excels at handling merge conflicts generated by composer.json and composer.lock. It, for the most part, resolves the majority of conflicts that get generated on its own. The only time I've seen it leave conflicts behind is when two different versions of a package have been updated relative to the base branch (e.g. you're merging two branches where both versions of the same package were updated, and each update is a different version).

I would just mention the tool as an aid for assisting with resolving conflicts from both files. It doesn't get enough love considering how much of a quality of life change I've experienced since I've started using it.

2020-11-02 11:16 UTC, naderman requested changes

2020-11-02 11:16 UTC, naderman commented on doc/articles/resolving-merge-conflicts.md
> +composer validate
This is not sufficient to check correctness, as it doesn't verify the set of packages in the lock file is actually installable after a manual text based merge. Would have to do an actual install (--dry-run)

2020-11-02 11:16 UTC, naderman commented on doc/articles/resolving-merge-conflicts.md
> +## B. Manually merging the `composer.json` and updating the `composer.lock` file
I'm not sure we should mention or advocate for this option at all? The correct way to merge is to reapply changes from the branch you are merging?

2020-11-02 11:16 UTC, naderman commented on doc/articles/resolving-merge-conflicts.md
> +When working as a team on the same Composer project, you'll eventually run into a scenario where multiple people added, updated or removed something in the `composer.json` and `composer.lock` files i
I think this article needs to explain, why text based merging of lock files is not possible.

E.g. if you have one branch which added A 1.0.0 requiring B ^1.0 and the lock file contains B 1.0.0 and another branch which added C 1.0.0 which conflicts with B <1.2 then text merge would lead to A 1.0.0, B 1.0.0 and C 1.0.0, which is actually invalid because C's conflict wasn't considered, and would require an upgrade of B.

2020-11-02 18:57 UTC, PrinsFrank commented on doc/articles/resolving-merge-conflicts.md
> +## B. Manually merging the `composer.json` and updating the `composer.lock` file
I wouldn't use this method myself but wanted to be as thorough as possible documenting all the options. But agreed, less is more here and better to learn the correct way immediately.

2020-11-02 18:58 UTC, PrinsFrank commented on doc/articles/resolving-merge-conflicts.md
> +composer validate
Cool, I didn't know that!

2020-11-02 19:36 UTC, stof commented on doc/articles/resolving-merge-conflicts.md
> +Choosing the correct [version constraints](../articles/versions.md) and making sure the packages adhere to [semantic versioning](https://semver.org/) when using [netx significant release operators](h
typo: `next` vs `netx`

2020-11-02 19:36 UTC, stof commented on doc/articles/resolving-merge-conflicts.md
> +Choosing the correct [version constraints](../articles/versions.md) and making sure the packages adhere to [semantic versioning](https://semver.org/) when using [netx significant release operators](h
The doc URL should be relative: `versions.md#next-significant-release-operators`

2020-11-03 11:00 UTC, naderman commented
@lpeabody based on just having read the README for that tool it actually improperly resolves situations regarding newly introduced conflicts in unrelated dependencies in separate branches, so I would definitely not mention it in official documentation, even though it may work fine in a lot of cases.

2020-11-03 16:45 UTC, lpeabody commented
@naderman thanks for the insight. Is there any chance you could take several minutes to post your analysis in an issue for that project?

2020-11-03 19:49 UTC, naderman commented
@lpeabody see my comment here https://github.com/composer/composer/pull/9386#discussion_r515902794 and the updated version of this article why text based merges and that's still what the other tool does, even if it understands JSON will not result in valid lock files. With Composer2 I suppose at least a composer update --lock will fail if the lock file isn't resolvable, so I suppose the tool isn't so bad in that at least it will hopefully error if the merge didn't work cleanly.

2020-11-03 20:24 UTC, PrinsFrank commented
This are really valuable discussions, thanks! I removed the section about the merge driver!

2020-11-10 20:09 UTC, PrinsFrank commented
@Seldaek @naderman The status of this PR is still "changes requested", but as far as I see I processed all requested changes. Am I missing something or am I misunderstanding the way github handles PRs?

2020-11-11 07:52 UTC, Seldaek commented
It's just remaining like that until someone else reviews, sorry haven't had time for this in a while but I'll try and get it merged this week.

2020-11-13 14:38 UTC, merged

2020-11-13 14:38 UTC, Seldaek commented
Thanks @PrinsFrank, this turned out to be a solid read :)