Fix HTTP status when Platform check failed
composer/composer pull request #9410
Opened 2020-11-03 20:11 UTC by jakubboucek

Composer 2 is checking platform requirements in runtime. It can cause shut down production in a lot of cases.

Here is big trouble the Error message is printed to output and replaced the Web Application. And although Composer is produced an Error message, it's introduced as a serious response of Web application ([status `200 OK`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200)).

It's Fail because the robots aren't correctly notified the response is Error and accepts the response as a valid response. It can cause mass burning of Website SEO reputation because the error message is indexed Search engine's robots and replaces the main content.

**Trust me its't very serious problem**, try to [**search "Composer detected issues in your platform"**](https://www.google.com/search?q=%22Composer+detected+issues+in+your+platform%22) for proof.

This PR is update Composer to send [status `503 Service Unavailable`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) when the platform check fails.

## FAQ

**App should never be deployed to production with Dev deps**

You right. But Composer 2 is extremely widespread among developers, regardless of their seniority. A lot of them are juniors. The problem is the platform check is in runtime with the most default usage of Composer, it's no requires any additional configuration in `composer.json`, no specific switch in `install`/`require` command. 

Considering the extent of possible damage is necessary to respect most general cases and a variety of uses.

**Check can be disabled by `--no-platform-reqs`, and similar ways…**

You right. But as I wrote above, platform check is Composer's default behavior and it's should be gently to prevent cause damage.

**Developer should ever check production environment before deploy**

You right. But s*it happens. The App can interfere with Platform requirements for a lot of reasons:

- Web hosting can silently change the server environment. Especially its problem on Shares web hosting.
- Developer can do a seemingly innocent update (`vendor-name/package-name 1.2.3 -> 1.2.4`) and does not expect any problem (Composer is not notified about changing platform-reqs during update).
- Developers just do mistakes - we are just humans.

2020-11-03 20:34 UTC, stof requested changes

2020-11-03 20:34 UTC, stof commented on src/Composer/Autoload/AutoloadGenerator.php
> +    http_response_code(503);
this won't work on PHP 5.3 (which is still supported by Composer 2.0), so this should at least be guarded by a version check

2020-11-03 20:59 UTC, jakubboucek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    http_response_code(503);
Hm, you right. 

Please help me to choose better way:
- `header("HTTP/1.1 503 Service Unavailable");` or
- `header(':', true, 503);` or
- `header('X-PHP-Response-Code: 404', true, 404);`

PHP 5.3 is now too far away for me, I must [consult it with Google](https://stackoverflow.com/questions/3258634/php-how-to-send-http-response-code), thanks for understand.

2020-11-03 21:22 UTC, jakubboucek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    http_response_code(503);
Changed to `header("HTTP/1.1 503 Service Unavailable");`

2020-11-03 21:55 UTC, ondrejmirtes commented
I agree something should be done about this. Maybe the check should run only in CLI SAPI?

2020-11-03 22:44 UTC, jakubboucek commented
@ondrejmirtes:
> Maybe the check should run only in CLI SAPI?

Checks on runtime in non-CLI SAPI is not completely bad idea. 

Just it must be implemented correctly and must be required by developer, instead of as default behavior in default setup.

2020-11-04 08:53 UTC, Seldaek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    header('HTTP/1.1 503 Service Unavailable');
Needs to be wrapped in `if (!headers_sent()) { ... }` for safety to avoid triggering errors.

2020-11-04 09:31 UTC, naderman commented
This needs to return a 500 Internal Server Error. The server is not unavailable in this case and it's not a temporary error that will potentially be fixed upon retry.

2020-11-04 10:15 UTC, jakubboucek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    header('HTTP/1.1 503 Service Unavailable');
You right. Updated.

The `!headers_sent()` condition is wrapping whole error reporting, not only `header()`, because it prevent to corrupting application response in half.

2020-11-04 10:18 UTC, jakubboucek commented
> @naderman This needs to return a 500 Internal Server Error. The server is not unavailable in this case and it's not a temporary error that will potentially be fixed upon retry and it is not server maintenance.

Good point, fixed.

2020-11-04 10:21 UTC, Seldaek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    header('HTTP/1.1 503 Service Unavailable');
I don't think that's good, because now it means we do not check/abort at all if headers were sent.

2020-11-04 11:03 UTC, dg commented on src/Composer/Autoload/AutoloadGenerator.php
> +    header('HTTP/1.1 503 Service Unavailable');
What about `echo '<!-- Composer detected issues in your platform` when SAPI is not CLI?

2020-11-04 11:29 UTC, Seldaek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    header('HTTP/1.1 503 Service Unavailable');
Please don't side-track this, this PR is only about the header. We have other improvements tracked in https://github.com/composer/composer/issues/9412

2020-11-04 11:33 UTC, jakubboucek commented
I suggest close this PR and replace it with #9414.

2020-11-04 11:57 UTC, jakubboucek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    header('HTTP/1.1 503 Service Unavailable');
@Seldaek What happen when Composer break rendering page in half? It's produce broken response and provide it as classic response – same result for SEPR and produce huge damage to SEO. 

I thinking and do some tests on few environments with result: it's all wrong, follow #9414.

2020-11-04 21:33 UTC, merged

2020-11-04 21:41 UTC, dkulyk commented
When header_send error will not show.
```php
if (\$issues && !headers_sent()) {
    header('HTTP/1.1 500 Internal Server Error');
    echo 'Composer detected issues in your platform:' . "\\n\\n" . implode("\\n", \$issues) . "\\n\\n";
    exit(104);
}
```
Maybe replace to
```php
if (\$issues) {
    headers_sent() || header('HTTP/1.1 500 Internal Server Error');
    echo 'Composer detected issues in your platform:' . "\\n\\n" . implode("\\n", \$issues) . "\\n\\n";
    exit(104);
}
```

2020-11-04 22:02 UTC, Seldaek commented
@dkulyk see https://github.com/composer/composer/pull/9414 - this is marked merged because it was included in the other PR, but the code hsa been replaced.