Fix platform check error message
composer/composer pull request #9418
Opened 2020-11-04 22:12 UTC by jakubboucek

Fixes bug from commit: 8c1355f448ec8087bf7ed468208f8d63794de909

- Prints error to output only when `ini_get('display_errors')` is truly,
- Add status 500 Internal server error to error message (see #9410 discussion)

2020-11-04 22:54 UTC, Seldaek requested changes

2020-11-04 22:54 UTC, Seldaek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    if (ini_get('display_errors')) {
I think you misunderstood here :) The point is to ensure that if we break a site and it has no errors visible, we print the message so it's not a blank page and gives a hint to people. Please revert.

2020-11-04 22:54 UTC, Seldaek commented
Makes sense to add the 500 back, totally forgot, thanks.

2020-11-04 23:05 UTC, Seldaek commented on src/Composer/Autoload/AutoloadGenerator.php
> +            header('HTTP/1.1 500 Internal Server Error');
actually seems like if display_errors is off, php leaves it 200, so please move this all the way up above line 738 so we always set the status code (unless headers have been sent already..).

2020-11-04 23:40 UTC, jakubboucek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    if (ini_get('display_errors')) {
@Seldaek That sounds like a very bad idea. 

**Reasons:**

- Developers is turns off this flat **to prevent any error message to output**. Their customers does not care about any internal bugs. It's look seriously non-proffesional.
- Developers often have in their projects [custom error handling](https://www.php.net/manual/en/function.set-error-handler.php) which is render custom error page. This `echo` is bypass clean handling.
- The message is leaking too detailed specifics about app/server configuration, it's very unsecure.

2020-11-04 23:49 UTC, jakubboucek commented on src/Composer/Autoload/AutoloadGenerator.php
> +            header('HTTP/1.1 500 Internal Server Error');
Hm, you right. I was really trusts the `trigger_error()` do it herself, but he didn't :-/

Moved as you said & rebased.

2020-11-05 08:14 UTC, Seldaek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    if (ini_get('display_errors')) {
Well I think we're gonna have to agree to disagree here :) 

- Now that I changed this to only check php version by default, and to only include non-dev dependencies in the check, the chance that this outputs some "internal bug" which is irrelevant is very unlikely. Stuff will most likely break if the PHP version is too low.
- The project error handler will in most cases not be loaded yet when the platform check runs as it is loaded with the autoloader, which is typically one of the first lines of code running.
- It's not leaking any application info anymore, as it now str_replaces the php version away when outputting on non-CLI SAPIs.

On top of that, if display_errors is on, the error will be shown already, so echoing it again on top is completely useless and duplicate.

2020-11-05 09:04 UTC, jakubboucek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    if (ini_get('display_errors')) {
Your arguments are strong, but I'm still convinced the direct printing error message to output in runtime (expecially at non-CLI SAPI) is subject of exceeding the boundary of responsibility that users can fairly expect. :)

Reverted, thanks.

2020-11-05 13:35 UTC, Seldaek commented on src/Composer/Autoload/AutoloadGenerator.php
> +    if (ini_get('display_errors')) {
👍  Thanks, merging then

2020-11-05 13:35 UTC, merged