Fix phpstan íssues
composer/composer pull request #9478
Opened 2020-11-13 17:08 UTC by adlacruzes

Hi,

after reading #9450, I think we can adopt an intermediate step when increasing phpstan level.

Level 2 show ~280 errors and could be hard fixing them without a baseline. Instead of increase full level we can add explicit rules from a higher level and fix errors progressively easier.

This PR fixes phpdocs issues and add some phpstan level 2 rules to config file.

2020-11-14 07:12 UTC, staabm approved these changes
Lgtm

2020-11-16 18:35 UTC, stof requested changes

2020-11-16 18:35 UTC, stof commented on src/Composer/Repository/PlatformRepository.php
> +     * @param mixed $name
`string` actually

2020-11-16 18:35 UTC, stof commented on tests/Composer/Test/Util/AuthHelperTest.php
> +     * @param mixed $origin
`string`

2020-11-16 18:35 UTC, stof commented on tests/Composer/Test/Util/AuthHelperTest.php
> +     * @param mixed $auth
`array`

2020-11-16 18:38 UTC, stof commented
> after reading #9450, I think we can adopt an intermediate step when increasing phpstan level.
> 
> Level 2 show ~280 errors and could be hard fixing them without a baseline. Instead of increase full level we can add explicit rules from a higher level and fix errors progressively easier.

I'd rather go to level 2 and introducing the baseline. that would be easier to maintain (no need to maintain a list of rules belonging to level 2) and would bring more value (new code would be checked at level 2).

the answer from @Seldaek on #9450 did not reject the usage of a baseline. This answer was rejecting the fact of adding a baseline without trying to fix as much reported issues as possible before generating it (so that moving to level 2 actually helps increasing the quality of the code).

2020-11-19 17:01 UTC, adlacruzes commented on src/Composer/Repository/PlatformRepository.php
> +     * @param mixed $name
Done

2020-11-19 17:02 UTC, adlacruzes commented on tests/Composer/Test/Util/AuthHelperTest.php
> +     * @param mixed $origin
Done

2020-11-19 17:03 UTC, adlacruzes commented on tests/Composer/Test/Util/AuthHelperTest.php
> +     * @param mixed $auth
Applied

2020-11-19 17:04 UTC, adlacruzes commented
Hi @stof, I rechecked mixed types and applied your correct suggestions.

The idea is to remove these rules once level 2 is reached, but its true we are introducing one more thing to maintain.

Should I limit this pull request to the proposed fixes, so we can merge it?

Thanks!

2020-11-19 18:58 UTC, stof commented
> The idea is to remove these rules once level 2 is reached, but its true we are introducing one more thing to maintain.

I'd rather do this by configuring level 2 with a baseline, and then work on emptying the baseline little by little to reach full level 2. this way, new code would be written at level 2 already.

2020-11-20 08:28 UTC, merged

2020-11-20 08:28 UTC, Seldaek commented
Going to merge this as it already fixes some things and adds more strictness, it goes in the right direction. But yes full level 2 or more with baseline probably makes more sense in the long run.

2020-11-20 14:21 UTC, adlacruzes commented
Thanks everyone!