Add example for "replace"
composer/composer pull request #9569
Opened 2020-12-23 09:40 UTC by mbrodala

2020-12-26 15:45 UTC, GrahamCampbell requested changes

2020-12-26 15:45 UTC, GrahamCampbell commented on doc/04-schema.md
> +        "acme/foo-legacy": "self.version"
When replacing a legacy package which is no longer receiving releases, you typically would not want to replace with `self.version`, actually. For example, fakerphp/faker replaces 1.9.1 and 1.9.2 with the same versions, only, and future releases do not replace the old package.

This example should be replaced with a subsplit package replacement example.

2021-01-07 22:16 UTC, Seldaek commented
Not sure having things people can copy paste without understanding anything will help here, or if it won't just add more confusion. Replace is a dangerous tool, which can be very easily misused, so people should read in depth..

2021-01-07 22:16 UTC, closed without merging

2021-01-08 07:46 UTC, mbrodala commented
@Seldaek Maybe my intention wasn't clear: just from reading it is not clear if `replace` is a `list` or a `map` in JSON. That's what I wanted to illustrate with the example. Not sure if these terms are already well-established yet but this should be mentioned.

2021-01-08 08:13 UTC, Seldaek commented
Ok, that is technically covered in the first line of https://getcomposer.org/doc/04-schema.md#package-links but it's a long section so I can see how it might be missed :)

2021-01-08 08:17 UTC, mbrodala commented
You are right. I must admit that I never read that part. ^_~

Maybe it would help to avoid the term _Lists_ in each option?

2021-01-08 08:31 UTC, Seldaek commented
Hopefully that does the job https://github.com/composer/composer/commit/19eef374d012df3d8bb36aa85eb687675b6d5369

2021-01-08 08:34 UTC, mbrodala commented
Yes, perfect. Thanks. :-)