Add --prefer-install arg and change default preferred-install to dist
composer/composer pull request #9603
Opened 2021-01-12 14:31 UTC by Seldaek

Fixes #9546 

cc @stof

2021-01-21 18:15 UTC, stof approved these changes

2021-01-21 20:02 UTC, nicolas-grekas commented on doc/06-config.md
> +- `auto` is the the legacy behavior where Composer uses `source` automatically
double "the"

2021-02-08 13:14 UTC, naderman requested changes

2021-02-08 13:14 UTC, naderman commented on doc/06-config.md
> +- `source` means Composer will install from `source` if there is one. This is
Please explain what installing from "source" means, that this is typically a checkout of the version control system used for the package.

2021-02-08 13:14 UTC, naderman commented on doc/06-config.md
> +- `dist` (the default as of Composer 2.1) means Composer installs from `dist`,
Please explain what dists are: typically zip files, e.g. in github case generated with git archive for a particular version.

2021-02-08 13:14 UTC, naderman commented on doc/03-cli.md
> +  packages, use `--prefer-install=auto`. See also [config.preferred-install](06-config.md#preferred-install).
Please document how this relates to the config option, what takes precendence?

2021-02-08 13:14 UTC, naderman commented on doc/03-cli.md
> +  packages, use `--prefer-install=auto`. See also [config.preferred-install](06-config.md#preferred-install).
Same for the other places this is referenced.

2021-02-24 14:59 UTC, stof commented on doc/03-cli.md
> +  packages, use `--prefer-install=auto`. See also [config.preferred-install](06-config.md#preferred-install).
I would say `for dev versions` instead of `for dev packages`, to clarify that this is not about `require` vs `require-dev` but about the stability of the package.

2021-02-24 14:59 UTC, stof commented on src/Composer/Command/BaseCommand.php
> +        $preferAuto = false;
seems unused

2021-04-07 12:19 UTC, Seldaek commented
Fixed all feedback items and rebased 👍🏻

2021-04-07 13:04 UTC, Seldaek commented on src/Composer/Command/BaseCommand.php
> +        }
Yeah sure will add that

2021-04-07 14:04 UTC, merged

2021-06-02 13:48 UTC, ondrejmirtes commented
Everyone who ever did `composer require phpstan/phpstan:dev-master` will thank you 😂  (the repository is huge, the dist zip is small).