Add --format option to `composer fund` command
composer/composer pull request #9678
Opened 2021-02-08 19:09 UTC by ochorocho

Hey,

currently building a little GUI around composer. I want to show funding information in the GUI.
Therefore i added `--format` option to the `composer fund` command which allows to output
fund details as JSON.

2021-02-09 00:15 UTC, stof requested changes

2021-02-09 00:15 UTC, stof commented on src/Composer/Command/FundCommand.php
> +        } elseif ($fundings && $format === 'json') {
this looks wrong to me. If there is no funding links found, the output should still be in JSON rather than plaintext when requesting json.

2021-02-09 00:15 UTC, stof commented on src/Composer/Command/FundCommand.php
> +                    $fundingJson[$vendor]['url'] = $url;
this output is wrong. It will keep only the last link of each vendor as it overrides it each time.

2021-02-09 00:15 UTC, stof commented on src/Composer/Command/FundCommand.php
> +                    $fundingJson[$vendor]['packages'] = implode(', ', $packages);
in JSON, a list of package as a JSON array is probably a lot better than a string containing a comma-separated list.

2021-02-09 08:34 UTC, ochorocho commented on src/Composer/Command/FundCommand.php
> +                    $fundingJson[$vendor]['packages'] = implode(', ', $packages);
Makes sense. Now the packages is an array.

2021-02-09 08:34 UTC, ochorocho commented on src/Composer/Command/FundCommand.php
> +                    $fundingJson[$vendor]['url'] = $url;
Thanks, missed this one.

2021-02-09 08:34 UTC, ochorocho commented on src/Composer/Command/FundCommand.php
> +        } elseif ($fundings && $format === 'json') {
True, fixed. :-)

2021-02-09 08:35 UTC, ochorocho commented
@stof thanks for reviewing this.

2021-02-10 08:47 UTC, Seldaek approved these changes

2021-02-11 12:39 UTC, stof requested changes

2021-02-11 12:39 UTC, stof commented on src/Composer/Command/FundCommand.php
> +                    $fundingJson[$vendor]['packages'] = $packages;
this is still wrong. The list of packages is not per vendor but per url. Otherwise, you loose all except the ones of the last link.

2021-02-11 20:33 UTC, ochorocho commented on src/Composer/Command/FundCommand.php
> +                    $fundingJson[$vendor]['packages'] = $packages;
@stof makes sense. Instead of building my own array the existing one is now used. So the issue should be fixed.
May i ask for another review? :-)

2021-02-24 15:27 UTC, stof approved these changes

2021-02-24 16:21 UTC, merged

2021-02-24 16:21 UTC, Seldaek commented
Thanks!