Add install-path and type to installedVersions.php and installed.php,…
composer/composer pull request #9699
Opened 2021-02-15 17:08 UTC by ochorocho

… add method to get installed packages by type

* Extended installedVersions.php and installed.php with `type` and `install_path`
* Added `getInstalledPackagesByType` to allow retrieval of of installed packages by a given type

@Seldaek your feedbeack is very welcome :-)

https://github.com/composer/composer/issues/9648

2021-02-16 13:05 UTC, ochorocho commented
Just had a look whats going on with phpstan issues.
Get 352 errors, even when running it on `master`

```
 [ERROR] Found 352 errors     
 ```

2021-02-16 14:07 UTC, stof requested changes

2021-02-16 14:07 UTC, stof commented on src/Composer/Repository/FilesystemRepository.php
> +                $installPath = ('' !== $path && null !== $path) ? $fs->findShortestPath($repoDir, $fs->isAbsolutePath($path) ? $path : getcwd() . '/' . $path, true) : null;
returning a relative path to the `installed.json` file looks bad to me: there is no way to actually resolve that to a usable path when actually using the InstalledVersions API as the path to the installed.json file is not exposed anywhere (and when you merged data from multiple vendor folders, the relative path will not always be relative to the same thing)

2021-02-16 16:48 UTC, ochorocho commented on src/Composer/Repository/FilesystemRepository.php
> +                $installPath = ('' !== $path && null !== $path) ? $fs->findShortestPath($repoDir, $fs->isAbsolutePath($path) ? $path : getcwd() . '/' . $path, true) : null;
Thanks for reviewing :-) Now using absolute paths.

2021-02-16 16:52 UTC, ochorocho commented
@stof can't wrap my head around this phpstan issue. It says `Call to an undefined static method`. The method is there, and it works locally and in "most" Actions except [windows](https://github.com/composer/composer/pull/9699/checks?check_run_id=1912251047)
Any idea what could cause this?

![grafik](https://user-images.githubusercontent.com/4623070/108094507-2c38a780-707f-11eb-9d06-27a8e5728050.png)

https://github.com/composer/composer/pull/9699/checks?check_run_id=1912250647

2021-02-24 20:09 UTC, Seldaek commented
@ochorocho sorry for the trouble but could you rebase this on latest master? I merged other things which conflict with your PR.

As for the phpstan error, you can ignore these, it's a quirk of the fact the InstalledVersions file used in CI does not yet contain the new methods until the PR gets merged.

2021-02-25 09:19 UTC, ochorocho commented
@Seldaek rebase done :-)

2021-03-08 13:11 UTC, ochorocho commented
FYI, all packages defined with `self.version` are missing paths.
Working on a fix right now.

2021-03-16 11:19 UTC, mvorisek commented on src/Composer/Repository/FilesystemRepository.php
> +                'install_path' => $installPath,
path should be relative to root project (or vendor?) directory to allow moving the project to somewhere else (realpath should be therefore NOT used as well)

2021-03-16 13:16 UTC, Seldaek commented on src/Composer/Repository/FilesystemRepository.php
> +                'install_path' => $installPath,
getInstallPath is usually an absolute path though, so the right way here is to do like it's doing at line 109 to initialize `$pkgArray['install-path']`. Possibly the paths could be kept there in an array per package and passed to `generateInstalledVersions` too so you don't have to redo it here.

2021-03-16 13:20 UTC, Seldaek commented on src/Composer/Repository/FilesystemRepository.php
> +                'install_path' => $installPath,
Also if `getInstallPath` returned `''` (like it does for packages of type `metapackage`) maybe we should set `install_path` to `null` to make this clear that there is no path/nothing installed. For the root package it should however be set to `''` representing getcwd().

2021-03-16 13:21 UTC, Seldaek commented on src/Composer/InstalledVersions.php
> +    public static function getInstalledPackagesByType($type = 'library')
I don't think I'd have a default value here. If you don't know what you are looking for you shouldn't be calling this :)

2021-03-16 13:30 UTC, Seldaek commented on src/Composer/InstalledVersions.php
> +        }
You are ignoring everything but the first array returned by getInstalled here, which is not good in case there are multiple autoloaders loaded.

```suggestion
        $packagesByType = array();

        foreach (self::getInstalled() as $installed) {
            foreach ($installed['versions'] as $name => $package) {
                if (isset($package['type']) && $package['type'] === $type) {
                    $packagesByType[] = $name;
                }
            }
        }
```

2021-03-16 13:31 UTC, Seldaek commented
> FYI, all packages defined with self.version are missing paths.

I am not sure what you mean, if you have more details maybe we can figure out a solution or at least identify the root cause.

2021-03-16 14:16 UTC, ochorocho commented on src/Composer/InstalledVersions.php
> +    public static function getInstalledPackagesByType($type = 'library')
Makes sense :-) Removed the default value.

2021-03-16 14:34 UTC, ochorocho commented
> > FYI, all packages defined with self.version are missing paths.
> 
> I am not sure what you mean, if you have more details maybe we can figure out a solution or at least identify the root cause.

`install_path` was missing for some packages in `vendor/composer/InstalledVersions.php`.
Checked it again after i applied your suggestion and it seems to work now.

Thank you.

Let me know if you need anything else. :-)

2021-03-16 16:14 UTC, Seldaek commented
Thanks for the fixes. The last thing open is https://github.com/composer/composer/pull/9699#pullrequestreview-613122433 which definitely needs fixing but then it looks good to me.

2021-03-16 16:30 UTC, stof commented on src/Composer/Repository/FilesystemRepository.php
> +                'install_path' => $installPath,
note that not only metapackages will have no install path. Replaced packages will also be in such case (as they are not installed anywhere)

2021-03-16 16:45 UTC, ochorocho commented on src/Composer/Repository/FilesystemRepository.php
> +                'install_path' => $installPath,
@stof thanks for that insight. So i reckon the problem described [here](https://github.com/composer/composer/pull/9699#issuecomment-800311716) still exists. I will verify that and let you know.

2021-03-16 17:38 UTC, stof commented on tests/Composer/Test/InstalledVersionsTest.php
> +            'install_path' => false,
`string|null` is a better type than `string|false` IMO

2021-03-17 12:25 UTC, ochorocho commented on tests/Composer/Test/InstalledVersionsTest.php
> +            'install_path' => false,
Changed to `null`

2021-03-17 12:29 UTC, ochorocho commented
> Thanks for the fixes. The last thing open is [#9699 (review)](https://github.com/composer/composer/pull/9699#pullrequestreview-613122433) which definitely needs fixing but then it looks good to me.

@Seldaek now using an array containing package name and its path and passing it to `generateInstalledVersions`.
The root package path is now `'install_path' => '',` and `metapackage` using `'install_path' => NULL,`

2021-03-17 15:10 UTC, stof commented on tests/Composer/Test/Repository/Fixtures/installed.php
> +        'install_path' => false,
this is wrong

2021-03-17 15:11 UTC, stof commented on src/Composer/Repository/FilesystemRepository.php
> +                'install_path' => $installPath,
the `InstalledVersions` API should still work with absolute paths. Otherwise, it is unusable as you won't be able to resolve them.

To make things portable, the solution is to dump paths using `__DIR__`, as done in the generated autoload files.

2021-03-17 15:12 UTC, stof commented on src/Composer/Repository/FilesystemRepository.php
> +                'install_path' => $installPath,
which would require dumping that in a PHP file rather than JSON.
The other option would be to resolve relative paths in the place reading the json file (and so knowing its location)

2021-03-17 15:29 UTC, Seldaek commented on src/Composer/Repository/FilesystemRepository.php
> +                'install_path' => $installPath,
Hmm yes `__DIR__` indeed would be good. `vendor/composer/installed.php` is indeed a PHP file not JSON so no problem there. It'll definitely make this PR more complex though as var_export can't be used as is anymore, sorry @ochorocho :)

2021-03-17 16:07 UTC, Seldaek commented on src/Composer/Repository/FilesystemRepository.php
> +                'install_path' => $installPath,
Yup that's the idea. You can check AutoloadGenerator to see examples of doing this.

2021-03-18 10:18 UTC, ochorocho commented on src/Composer/Repository/FilesystemRepository.php
> +                'install_path' => $installPath,
@Seldaek created a method to dump the version array including `__DIR__`.
Ready for review :-)

2021-03-18 10:20 UTC, ochorocho commented on tests/Composer/Test/Repository/Fixtures/installed.php
> +        'install_path' => false,
Changed to `'install_path' => '',`.

Thanks you!

2021-03-18 10:53 UTC, stof reviewed
I don't see any tests covering the generation of the `install_path` key

2021-03-18 10:53 UTC, stof commented on src/Composer/InstalledVersions.php
> +    public static function __constructStatic() {}
why `__constructStatic` ? names prefixed by `__` are soft-reserved by PHP for magic methods, and this is not one of them.

2021-03-18 10:53 UTC, stof commented on src/Composer/InstalledVersions.php
> +InstalledVersions::__constructStatic();
why ? this is a no-op

2021-03-18 10:53 UTC, stof commented on src/Composer/Repository/FilesystemRepository.php
> +                $lines .= $folder . '\'' . $stringContent . "',\n";
you should still be using `var_export` to export the string literal, rather than rebuilding it in userland (in an incomplete way)

2021-03-18 10:53 UTC, stof commented on src/Composer/Repository/FilesystemRepository.php
> +            $installPath = $package instanceof RootPackageInterface ? '' : $installPaths[$package->getName()];
this is wrong. the relative path from the location of the installed.php file to the root package is not the empty string.

2021-03-18 12:04 UTC, ochorocho commented on src/Composer/Repository/FilesystemRepository.php
> +            $installPath = $package instanceof RootPackageInterface ? '' : $installPaths[$package->getName()];
This is the final result in `InstalledVersions.php` so i reckon the path correct:
```php
self::$installed = array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . DIRECTORY_SEPARATOR . '',
        'aliases' => array(
            0 => '2.1.x-dev',
        ),
        'reference' => 'a614587ec91031b99ab23b385838f6d9641c847d',
        'dev-requirement' => true,
        'name' => 'composer/composer',
    ),
   ....
```

2021-03-18 12:21 UTC, Seldaek commented on src/Composer/Repository/FilesystemRepository.php
> +            $installPath = $package instanceof RootPackageInterface ? '' : $installPaths[$package->getName()];
root should have an install_path of `__DIR__ . '/../../'` for composer, but the result should be dependent on the vendor-dir, so it should really compute the relative path from vendor-dir/composer to getcwd() to find the root install path.

2021-03-18 13:02 UTC, ochorocho commented on src/Composer/InstalledVersions.php
> +    public static function __constructStatic() {}
Makes sense, will rename it.

2021-03-18 13:09 UTC, ochorocho commented on src/Composer/Repository/FilesystemRepository.php
> +                $lines .= $folder . '\'' . $stringContent . "',\n";
Well, i need this to be able to write `__DIR__ . DIRECTORY_SEPARATOR . ` to the PHP file and not the resulting path.
Happy to have any suggestions to avoid using my own method.

2021-03-18 16:09 UTC, stof commented on src/Composer/Repository/FilesystemRepository.php
> +                $lines .= $folder . '\'' . $stringContent . "',\n";
Your generated line is `__DIR__ . DIRECTORY_SEPARATOR .` followed by a string literal. I'm talking only about the string literal, not about the whole line.

2021-03-18 16:12 UTC, stof commented on src/Composer/Repository/FilesystemRepository.php
> +                $from = $to . DIRECTORY_SEPARATOR . $vendorDir . DIRECTORY_SEPARATOR . 'composer';
no need to do your own processing of the vendor-dir config. The `$from` is the `$repoDir` that we have in `->write()`, i.e. the folder in which we are generating the file. You only need to pass it as an argument in this private method

2021-03-18 17:10 UTC, ochorocho commented on src/Composer/Repository/FilesystemRepository.php
> +                $from = $to . DIRECTORY_SEPARATOR . $vendorDir . DIRECTORY_SEPARATOR . 'composer';
Thanks for that hint. Changed it.

2021-03-18 17:15 UTC, ochorocho commented
@Seldaek tried to fix `testRepositoryWritesInstalledPhp` but failed. :-( 
The path is confusing me `/foo/bar/vendor/woop/woop`.

Can you give me any advice to get this test running again?

2021-04-01 08:35 UTC, ochorocho commented
@Seldaek all tests passed now. Branch is up to date with master.

2021-05-21 12:48 UTC, Seldaek commented
@ochorocho thanks for this, I rebased it again and squashed commits to clean up a little then reviewed in depth and did some changes (some of it are kinda unrelated to this PR, just other things I noticed needed tweaking before 2.1 for InstalledVersions while I was poking around). Have a look at my individual commits if you're interested in more details.

I think this is mergeable now, but happy if someone else has a second to review again.

2021-05-21 13:54 UTC, ochorocho reviewed
Looks good to me.

Thank you! :-)

2021-05-24 08:29 UTC, merged