Detect and output a better hint for cyclic dependencies
composer/composer pull request #9902
Opened 2021-05-21 09:15 UTC by Seldaek

Fixes #9837

2021-05-21 09:28 UTC, naderman requested changes
I actually think this should entirely be rewritten to put less of a focus on cyclic/circular dependencies and instead make it clear that a dependency on something which depends on a specific root package version is the problem.

2021-05-21 09:28 UTC, naderman commented on doc/articles/troubleshooting.md
> +## Cyclic / circular dependencies
Cycling or circular dependencies are a normal thing and don't cause problems. What this describes is rather a Cyclic / circular dependency including the root package, so I think the title too should make it clear this is only about situations involving the root package.

2021-05-21 09:28 UTC, naderman commented on doc/articles/troubleshooting.md
> +Cyclic dependencies commonly causes issues in two cases:
Here to you need to be clear, cyclic dependencies do not typically cause any of these problems, a cyclic dependency on the root package may.

2021-05-21 09:28 UTC, naderman commented on src/Composer/DependencyResolver/Problem.php
> +                    'satisfiable by '.self::getPackageList($nextRepoPackages, $isVerbose).' from '.$nextRepo->getRepoName().' but the root package can not be updated. This is due to a cyclic dependen
This is confusing, what is due to a cyclic dependency? The root package cannot be updated?

2021-05-25 10:36 UTC, naderman commented on tests/Composer/Test/Fixtures/installer/circular-dependency-errors.test
> +    - requires/root 1.0.0 requires root/pkg ^1.0 -> satisfiable by root/pkg[1.0.0] from package repo (defining 2 packages) but the root package can not be updated so it is not installable. See https:
```suggestion
    - requires/root 1.0.0 requires root/pkg ^1.0 -> satisfiable by root/pkg[1.0.0] from package repo (defining 2 packages) but root/pkg is the root package and cannot be modified. See https://getcomposer.org/cyclic-dep for details and assistance.
```

2021-05-25 20:58 UTC, naderman approved these changes

2021-05-25 20:58 UTC, merged

2021-05-25 21:06 UTC, Seldaek commented
Added https://github.com/composer/composer/commit/0dce0f80f12543304fb0f1f755fb7bf9dbecfc9e to this :)